### ISSUE TITLE
Turn on USE_MESA: True Execution command fails

### ISSUE THREAD

**Issue by chesongsong** [facebookresearch/AnimatedDrawings#100]
When USE_MESA is False, the code execution is ok, but when I set USE_MESA to True, the program reports an error

USE_MESA: False
<img width="1675" alt="image" src="https://user-images.githubusercontent.com/21020093/232201837-4471ee8b-334d-4022-90d8-965869825673.png">
USE_MESA: True

<img width="1669" alt="image" src="https://user-images.githubusercontent.com/21020093/232201873-b3dca165-b4a4-4065-9479-42061834246d.png">

`Python 3.11.3 (main, Apr  7 2023, 19:25:52) [Clang 14.0.0 (clang-1400.0.29.202)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from animated_drawings import render
>>> render.start('./examples/config/mvc/export_mp4_example.yaml')
 Writing video to: /Users/chejinsong/Desktop/animated-server/AnimatedDrawings/video.mp4
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 779/779 [00:49<00:00, 15.60it/s]
>>> render.start('./examples/config/mvc/export_mp4_example.yaml')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/chejinsong/Desktop/animated-server/AnimatedDrawings/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/chejinsong/Desktop/animated-server/AnimatedDrawings/animated_drawings/view/view.py", line 43, in create_view
    from animated_drawings.view.mesa_view import MesaView
  File "/Users/chejinsong/Desktop/animated-server/AnimatedDrawings/animated_drawings/view/mesa_view.py", line 8, in <module>
    from OpenGL import GL, osmesa
  File "/usr/local/lib/python3.11/site-packages/OpenGL/osmesa/__init__.py", line 2, in <module>
    from OpenGL.raw.osmesa.mesa import *
  File "/usr/local/lib/python3.11/site-packages/OpenGL/raw/osmesa/mesa.py", line 41, in <module>
    @_f
     ^^
  File "/usr/local/lib/python3.11/site-packages/OpenGL/raw/osmesa/mesa.py", line 10, in _f
    function,_p.PLATFORM.OSMesa,
             ^^^^^^^^^^^^^^^^^^
AttributeError: 'DarwinPlatform' object has no attribute 'OSMesa'
>>> 

`

**Comment by hjessmith** [comment]
Thanks for reporting this issue. What operating system are you using?

**Comment by chesongsong** [comment]
<img width="280" alt="image" src="https://user-images.githubusercontent.com/21020093/232654077-cfd2cb29-b64b-4adb-a468-d25ac97972b4.png">

**Comment by hjessmith** [comment]
I've only ever gotten mesa headless rendering to work with Ubuntu. I think it should be possible to do so with macos, but I'm not sure what dependencies/steps are needed. If you figure it out and submit a PR, I would be grateful.

**Comment by yuleiqin** [comment]
> 

hi, when I run the program headless rendering with a CentOS7 station (via ssh), I got the error:

(I already followed 
1.  conda install -c conda-forge libstdcxx-ng=12
2.  export DISPLAY=":1"
3. export MESA_GL_VERSION_OVERRIDE=3.3
4. export MESA_GLSL_VERSION_OVERRIDE=330
)

Would you please give some suggestions? Thanks a lot in advance!

  File "/youtu-reid/yuleiqin/code_utils/AnimatedDrawings/animated_drawings/view/shaders/shader.py", line 29, in _compile_shader
    assert False, msg
AssertionError: Compile failed for GL_VERTEX_SHADER (GL_VERTEX_SHADER)
0:5(10): error: GLSL 3.30 is not supported. Supported versions are: 

1: // Copyright (c) Meta Platforms, Inc. and affiliates.
2: // This source code is licensed under the MIT license found in the
3: // LICENSE file in the root directory of this source tree.
4: 
5: #version 330 core
6: uniform mat4 model;
7: uniform mat4 view;
8: uniform mat4 proj;
9: 
10: layout(location = 0) in vec3 pos;
11: layout(location = 1) in vec3 color;
12: 
13: flat out int vertex_id;
14: 
15: out vec3 ourColor;
16: 
17: void main(){
18:    gl_Position = proj * view * model * vec4(pos, 1);
19: 
20:    vertex_id = gl_VertexID;
21: 
22:    ourColor = color;
23: }

**Comment by liuwenran** [comment]
@yuleiqin I meet the same problem, have you solved this?

**Comment by LIANGSHUOWEN** [comment]
> I meet the same problem, have you solved this?

I meet the same problem, have you solved this?
