### ISSUE TITLE
How to configure motion config file and retarget config file

### ISSUE THREAD

**Issue by chesongsong** [facebookresearch/AnimatedDrawings#101]
If there is a tutorial, I hope you can provide me with a tutorial address

**Comment by Linspirit98** [comment]
Same question. Do we have to calculate the config file by hand?

**Comment by hjessmith** [comment]
Hi @chesongsong @Linspirit98 

I haven't made a tutorial for this and, as of now, you do need to make them by hand. But the motion configs are pretty straightforward and short. For guidance, look at some of the example ones located [here](https://github.com/facebookresearch/AnimatedDrawings/tree/main/examples/config/motion).

I also wrote some documentation on what each element in the motion config does [here](https://github.com/facebookresearch/AnimatedDrawings/tree/main/examples/config/motion).

Retarget config files are more complicated than motion config files. But you can reuse one with multiple different motion config files, as long as the BVH skeleton doesn't change. 
Take a look the [documentation](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md#retarget-config-file) and [examples](https://github.com/facebookresearch/AnimatedDrawings/tree/main/examples/config/retarget)

**Comment by chesongsong** [comment]
If I convert my dancing video to BVH, do I need to manually debug the corresponding motion config and retarget config? Can these two files be automatically generated according to BVH?

**Comment by hjessmith** [comment]
They cannot be fully automatically generated from the BVH file, as the skeleton hierarchy and joint names can be different in each BVH, and this information must be properly reflected in the retarget config.

A halfway measure might be to create retarget config files that work for some of the more common skeletal hierarchies, such as those used by Mixamo or output by Rokoko.  It still might require some manual editing, but would be better than nothing.

**Comment by chesongsong** [comment]
Can the interface of sketch.metademo.com be used externally

**Comment by hjessmith** [comment]
Sorry, @chesongsong, the interface of sketch.metademolab.com cannot be used externally.
