### ISSUE TITLE
Segmentation fault when saving to video or gif 

### ISSUE THREAD

**Issue by derrdji** [facebookresearch/AnimatedDrawings#102]
```
> $ python gif.py
> Imports successful!
>  Writing video to: /home/usr/projects/animated-drawing/video.gif
> 100%|█████████████████████████████████████████████████████████████████████████████████| 339/339 [00:10<00:00, 33.21it/s]
> Segmentation fault
```

Same thing happens to save to a video, it finishes 100% but then seg fault

**Comment by hemangjoshi37a** [comment]
Solution :
A segmentation fault can occur when a program tries to access a memory location that it is not allowed to access. This can happen for various reasons, such as a bug in the code, a memory leak, or an issue with the system configuration.

To troubleshoot the issue, the user could try the following:

Check if the issue occurs consistently or if it is intermittent. If it is intermittent, it could be a hardware issue or a system resource issue.
Check if the issue occurs with other scripts or programs that save videos or GIFs. If it does, it could be a system configuration issue.
Check if the issue occurs with different input data. If it does, it could be a bug in the code.
Check if there are any memory leaks or other issues with the code that could be causing the segmentation fault.
Try running the script in a different environment or on a different system to see if the issue persists.
If the issue persists, the user could try reaching out to the maintainers of the AnimatedDrawings repository for further assistance or submit a bug report. They could provide more details about their system configuration and the steps they took to reproduce the issue.

**Comment by Aditya-Naresh** [comment]
Any update on this issue?

**Comment by hjessmith** [comment]
I haven't come across a segfault in the code that would manifest like this before. Does it also occur when outputting an .mp4? Can you successfully run any of the examples in the readme, or does this always occur? What sort of development environment are you encountering this in?
