### ISSUE TITLE
Remote end closed connection without response

### ISSUE THREAD

**Issue by justinduynguyen** [facebookresearch/AnimatedDrawings#105]
![image](https://user-images.githubusercontent.com/18099515/232321357-4766f1bb-5bba-46e9-bd99-1afc94acc07e.png)
I got this issue when try to animate own drawing.
Thank u for your helps.

**Comment by hjessmith** [comment]
Hi @justinduynguyen.

I'm unsure what's causing this issue, and whether it's something with the Docker container or TorchServe. If you ping the server again after you've received this message, does it still return 'healthy'?
If you ping the

**Comment by justinduynguyen** [comment]
> Hi @justinduynguyen.
> 
> I'm unsure what's causing this issue, and whether it's something with the Docker container or TorchServe. If you ping the server again after you've received this message, does it still return 'healthy'?

It returns this message:
`curl: (52) Empty reply from server`

**Comment by justinduynguyen** [comment]
> It looks like there's an issue with TorchServe then. Try increasing the RAM available to the docker container to 16 gb and try again.

I was increasing the RAM available to 16GB or 32GB even but still not working.
This log from docker
<img width="1093" alt="image" src="https://user-images.githubusercontent.com/18099515/232760152-e11943aa-12f1-4817-b655-3c0a6e881527.png">

**Comment by hjessmith** [comment]
I'm not sure what's causing the issue. You could try rebooting the docker, rebuilding it, or [finding and killing whatever is using port 7070](https://stackoverflow.com/questions/11583562/how-to-kill-a-process-running-on-particular-port-in-linux).

**Comment by pineappleKID** [comment]
I meet the same problem. It works after my increasing RAM available to the docker container to **32** GB (not worked for 16 GB).
