### ISSUE TITLE
能在demo网站传一下你的舞蹈吗？

### ISSUE THREAD

**Issue by conancheng** [facebookresearch/AnimatedDrawings#108]
![image](https://user-images.githubusercontent.com/6675724/219223438-2c93f9cb-d4b5-45e9-a433-149ed76affa6.gif)
![image](https://user-images.githubusercontent.com/24214834/232371928-fe29709c-f826-4822-88c8-0f94ae1f1310.png)
想给孩子做一个跟你一样的视频，看了下demo网站里面没有这个舞蹈动作，可以帮忙更新一下吗？

**Comment by hjessmith** [comment]
I have no plans to add my particular motions to the github repo, but I will note this feature request to add more motion clips into the github project.

**Comment by hjessmith** [comment]
I'm adding my particular dancing motion (shown in banner animation) as an additional example for the readme. Hopefully it is helpful to you.
