### ISSUE TITLE
Difficulty in marking the front/back part of the body in BVH

### ISSUE THREAD

**Issue by gsrathoreniks** [facebookresearch/AnimatedDrawings#110]
Consider this example 
<img width="200" alt="Screenshot 2023-04-17 at 1 39 00 PM" src="https://user-images.githubusercontent.com/19241334/232456873-9aa29dc6-5cbf-4b40-9990-7b9b8427e35f.png">

Uploading animation.mp4…

even after marking all the joints correctly, Its difficult to define which one is in front and which one is in back, which is making output weird.

**Comment by hjessmith** [comment]
You're right. It won't look good on a character posed like this. But that's a limitation of how the system is set up. I have no plans to address this, as it would probably require doing a per-part segmentation of the figure, which is a significant change.
