### ISSUE TITLE
ValueError: Input X contains NaN. PCA does not accept missing values encoded as NaN natively.

### ISSUE THREAD

**Issue by justinduynguyen** [facebookresearch/AnimatedDrawings#122]
```
ValueError: Input X contains NaN.
PCA does not accept missing values encoded as NaN natively. For supervised learning, you might want to consider sklearn.ensemble.HistGradientBoostingClassifier and Regressor which accept missing values encoded as NaNs natively. Alternatively, it is possible to preprocess the data, for instance by using an imputer transformer in a pipeline or drop samples with missing values. See https://scikit-learn.org/stable/modules/impute.html You can find a list of all estimators that handle NaN values at the following page: https://scikit-learn.org/stable/modules/impute.html#estimators-that-handle-nan-values
```
this is my setup:
bvh file: custom_hik.bvh (export from rokoko)
my export settings:
![image](https://user-images.githubusercontent.com/18099515/233015822-0719aee1-da1f-4b43-99f4-ca01d8b3390c.png)
motion config: custom.yaml
retarget config: custom_retarget.yaml
[custom.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11270814/custom.zip)
Thank you in advance

**Comment by yslion** [comment]
I got the same err before , try to edit  the  motion yaml , the last line ,  if  it is  up: +z  ,  change to  up: +y    .( if it is  y  try to z :)  )

**Comment by justinduynguyen** [comment]
> I got the same err before , try to edit the motion yaml , the last line , if it is up: +z , change to up: +y .( if it is y try to z :) )

thank u, it worked for me
