### ISSUE TITLE
Prompt this error ： Segmentation fault (core dumped) 

### ISSUE THREAD

**Issue by DevinXiaoBai** [facebookresearch/AnimatedDrawings#127]
A large number of these processes are found in the process:

/opt/conda/bin/python /opt/conda/lib/python3.10/site-packages/ts/model_service_worker.py --sock-type unix --sock-name /tmp/.ts.sock.9044 --metrics-config /opt/conda/lib/python3.10/site-packages/ts/configs/metrics.yaml

It takes up a lot of memory. How to solve it?

**Comment by hjessmith** [comment]
Troubleshooting torchserve is outside my scope of support. Try their help docs or open an issue in their Github: https://pytorch.org/serve/

**Comment by Ajaypawar02** [comment]
any update regarding this error?? How to solve this
