### ISSUE TITLE
How can I change it to Run on gpu；

### ISSUE THREAD

**Issue by ARDUJS** [facebookresearch/AnimatedDrawings#130]
When I run the sample code:
`
  from animated_drawings import render
  render.start('./examples/config/mvc/export_mp4_example.yaml')
`
find that the gpu usage is 0；
How can I change it to Run on gpu；

**Comment by hjessmith** [comment]
There isn't any particularly complex shader logic, so I haven't explicitly tried to speed things up via the GPU. I doubt it would make things render much faster. 

Feel free to submit a PR if you choose to pursue this.
