### ISSUE TITLE
Not grabbing entire drawing...

### ISSUE THREAD

**Issue by everythingability** [facebookresearch/AnimatedDrawings#131]
Hi,

so I starting from scratch here... on a clean new Mac and have insalled Anaconda and Docker - there goes 8GB of space :-) and following your excellent instructions have got things running. I have used python before but I'm only a hobby level coder. 

I want to use my daughters drawings - the first one worked fabulously. The second however gives many of these errors as it runs.
![birb](https://user-images.githubusercontent.com/96276/233367313-1aeb6e11-a184-4cae-af3d-a14dc5a8010c.png)

`point [[0.44142616 0.13921902]] not inside or on edge of any triangle in mesh. Skipping it`

and then the result gif is like this...
![video](https://user-images.githubusercontent.com/96276/233367424-e4a0b6fb-0949-4112-91ab-0b72db0bc0e9.gif)

... or when I upped the gutter on the image, making the canvas bigger...
![video3](https://user-images.githubusercontent.com/96276/233367573-cb4388da-6188-4843-851b-f2e48981ba52.gif)

The generated mask image is way off...
![mask](https://user-images.githubusercontent.com/96276/233367753-3608b7b7-7d4a-4c1a-beb0-e7b2b30a41bb.png)

I tried using annotations_to_animation.py but the image was already clipped at the edges.

Do you have any tips for stylistic changes to the image which would make the image detection more reliable ( I tried adding a black stroke to the image and got this)... but it still clips...
![video](https://user-images.githubusercontent.com/96276/233369991-8607b4d6-1bb2-47f3-9861-a4d5a14a8d18.gif)

Are there optimum dimensions or resolution?  I tried ensuring alpha transparency in the png...

Aha... I think I've got it...  I made the picture much bigger ... 3000+ pixel with the image (small) in the centre.
![birb](https://user-images.githubusercontent.com/96276/233371304-0849732b-d844-4e39-836e-6398404c9607.png)

THEN I got this...
![video](https://user-images.githubusercontent.com/96276/233371411-0e1a2515-e937-4f43-8245-d812d6c83e14.gif)

...which is much better but it's still clipping slightly... and when I try and fix_annotations I see this...
<img width="338" alt="Fix_Annotations" src="https://user-images.githubusercontent.com/96276/233372410-b81c9496-d1a0-4749-ae33-bc9e9e57429b.png">

Our plan is to generate sprite sheets (or folders of numbered images) so she can make a game with them, so I assume I can modify the motion params (somewhere) for "walking", for example, so that the character doesn't move.

Lastly, that slight white border might get a bit annoying (given the image itself had no background)... looks at bit like characters from Paddington Bear when I was kid https://youtu.be/mClA14WQFu8?t=55 ) but we will be shrinking the generated image down a lot so it may get lost in the shrinkage... 

Thanks!

**Comment by hjessmith** [comment]
Hello,

If the tools for automatically creating the texture.png, mask.png, and joints aren't working, you can also create them by hand. texture.png should be a cropped RGB image. mask.png should be a grayscale image with the same dimensions as texture.png. And you can reuse an existing char_config.yaml from your previous attempts. Run it through the annotation fixer to make sure it looks good.

**Comment by everythingability** [comment]
Hi,

I'll give that whirl and see how I get on....

cheers, 

Tom

**Comment by everythingability** [comment]
OK, so wow! That has made a huge difference...

![video](https://user-images.githubusercontent.com/96276/233591494-d7f77c73-2fa7-4ed6-ac54-2c2b8168c9cf.gif)

Can I kind of, by way of a workflow, replace the texture.png and mask.png with any images (same size) and then run fix_annotations.py to tweak the skelton, then image_to_animation.py? to get a gif?

Continuing, or given that ideally I want to generate idle, walk, dance, dab animations for any given character image, will it be better to duplicate and adapt image_to_animation.py (kind of as shown in the documentation above)?  

This is great fun!

**Comment by hjessmith** [comment]
Glad you're enjoying the tool :)

Yes, you can replace texture.png and mask.png with whatever you want and run fix_annotations.py to tweak the skeleton. The files that result from that should be good to go, and you can create an animation from them.
