### ISSUE TITLE
ValueError: 'RightArm' is not in list

### ISSUE THREAD

**Issue by armavrdsp** [facebookresearch/AnimatedDrawings#133]
when i use config/motion/jumping_jacks.yaml to create animation, it happen. how can i solve this error? my image is 
![Uploading joint_overlay.png…]()

**Comment by armavrdsp** [comment]
![joint_overlay](https://user-images.githubusercontent.com/16572498/233524718-becbb60c-2631-46bb-9a3d-a8589180c5fd.png)
image

**Comment by hjessmith** [comment]
Try using the retarget config specified within 'examples/config/mvc/different_bvh_skeleton_example.yaml'

**Comment by armavrdsp** [comment]
> Try using the retarget config specified within 'examples/config/mvc/different_bvh_skeleton_example.yaml'

thx, I try this: python image_to_animation.py image/niuniu2.png niuniu config/motion/jumping_jacks.yaml config/mvc/different_bvh_skeleton_example.yaml

but it happen "KeyError: 'char_starting_location'"

**Comment by armavrdsp** [comment]
run : python image_to_animation.py image/niuniu2.png niuniu config/motion/jumping_jacks.yaml config/retarget/cmu1_pfp.yaml

it work

**Comment by armavrdsp** [comment]
it is solved
