### ISSUE TITLE
help， can you provide a docker image

### ISSUE THREAD

**Issue by ARDUJS** [facebookresearch/AnimatedDrawings#134]
can you provide a docker image？
when i run， `docker build -t docker_torchserve .`
always failed，the network often timeouts in the docker installation environment

**Comment by littleningmeng** [comment]
I got an error when running docker build.   
```bash
 => ERROR [ 2/12] RUN apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     c  16.4s
------
 > [ 2/12] RUN apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     ca-certificates     curl     python3-pip     vim     sudo     default-jre     git     gcc     build-essential     && rm -rf /var/lib/apt/lists/*:
#7 10.22 Err:1 http://deb.debian.org/debian bullseye InRelease
#7 10.22   Connection failed [IP: 151.101.110.132 80]
#7 15.52 Get:2 http://deb.debian.org/debian-security bullseye-security InRelease [48.4 kB]
#7 15.76 Get:3 http://deb.debian.org/debian bullseye-updates InRelease [44.1 kB]
#7 15.91 Get:4 http://deb.debian.org/debian-security bullseye-security/main arm64 Packages [233 kB]
#7 16.34 Get:5 http://deb.debian.org/debian bullseye-updates/main arm64 Packages [12.0 kB]
#7 16.36 Fetched 337 kB in 16s (20.8 kB/s)
#7 16.36 Reading package lists...
#7 16.38 W: Failed to fetch http://deb.debian.org/debian/dists/bullseye/InRelease  Connection failed [IP: 151.101.110.132 80]
#7 16.38 W: Some index files failed to download. They have been ignored, or old ones used instead.
#7 16.39 Reading package lists...
#7 16.41 Building dependency tree...
#7 16.41 Reading state information...
#7 16.41 Package default-jre is not available, but is referred to by another package.
#7 16.41 This may mean that the package is missing, has been obsoleted, or
#7 16.41 is only available from another source
#7 16.41
#7 16.41 Package build-essential is not available, but is referred to by another package.
#7 16.41 This may mean that the package is missing, has been obsoleted, or
#7 16.41 is only available from another source
#7 16.41
#7 16.41 Package gcc is not available, but is referred to by another package.
#7 16.41 This may mean that the package is missing, has been obsoleted, or
#7 16.41 is only available from another source
#7 16.41
#7 16.41 Package python3-pip is not available, but is referred to by another package.
#7 16.41 This may mean that the package is missing, has been obsoleted, or
#7 16.41 is only available from another source
#7 16.41
#7 16.41 E: Package 'python3-pip' has no installation candidate
#7 16.41 E: Unable to locate package vim
#7 16.41 E: Package 'default-jre' has no installation candidate
#7 16.41 E: Package 'gcc' has no installation candidate
#7 16.41 E: Package 'build-essential' has no installation candidate
------
executor failed running [/bin/sh -c apt-get update &&     DEBIAN_FRONTEND=noninteractive apt-get install --no-install-recommends -y     ca-certificates     curl     python3-pip     vim     sudo     default-jre     git     gcc     build-essential     && rm -rf /var/lib/apt/lists/*]: exit code: 100
```

**Comment by littleningmeng** [comment]
finally, I solved this problem with my VPN network……

**Comment by wimi321** [comment]
> 

I have the same problem, how did you fix it? Did you set up a global VPN on the router?

**Comment by littleningmeng** [comment]
> > 
> 
> I have the same problem, how did you fix it? Did you set up a global VPN on the router?

Yes, I used a global VPN.  
Maybe I can push my image to docker.io  later.

**Comment by littleningmeng** [comment]
I pushed my image to docker hub.  
you can try pull it from my repo.  
```bash
docker pull qingweihe/docker_torchserve:latest
```

**Comment by wimi321** [comment]
> 

Thank you very much. I'm too busy with work and haven't had time to build a global VPN ....

**Comment by yxf1213** [comment]
> I pushed my image to docker hub. you can try pull it from my repo.
> 
> ```shell
> docker pull qingweihe/docker_torchserve:latest
> ```

Hi, I use your repo and no error is reported, but after executing the next docker run command, it still prompts that docker_torchserve cannot be found, I wonder if you can help to solve this problem, thank you very much.
The error message is as follows
(animated_drawings) C:\Users\yxf\.conda\envs\animated_drawings\AnimatedDrawings\torchserve>docker run -d --name docker_torchserve -p 8080:8080 -p 8081:8081 docker_torchserve
Unable to find image 'docker_torchserve:latest' locally
docker: Error response from daemon: pull access denied for docker_torchserve, repository does not exist or may require 'docker login': denied: requested access to the resource is denied.
See 'docker run --help'.

**Comment by littleningmeng** [comment]
> 

you can try to login  to docker hub before pull the image  
```bash
docker login
# enter you username and passwd
```
if you don't have a docker hub account, you can try to register in [docker](https://www.docker.com/)

**Comment by yxf1213** [comment]
> > 
> 
> 您可以尝试在拉取图像之前登录到 docker hub
> 
> ```shell
> docker login
> # enter you username and passwd
> ```
> 
> 如果没有docker hub账号，可以尝试在[docker中注册](https://www.docker.com/)

![image](https://user-images.githubusercontent.com/119831245/234481644-3d375bd5-0505-469c-a816-e40a943ec19c.png)
I've logged into my docker hub account and run your command, and I see that it should have worked, but why does the next command still say docker_torchserve cannot be found, I hope you can help me again to see if there is another solution, I'm doing this on windows and I've tried on ubuntu, but in the end I can't find docker_torchserve.

**Comment by littleningmeng** [comment]
> > > 
> > 
> > 
> > 您可以尝试在拉取图像之前登录到 docker hub
> > ```shell
> > docker login
> > # enter you username and passwd
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > 如果没有docker hub账号，可以尝试在[docker中注册](https://www.docker.com/)
> 
> ![image](https://user-images.githubusercontent.com/119831245/234481644-3d375bd5-0505-469c-a816-e40a943ec19c.png) I've logged into my docker hub account and run your command, and I see that it should have worked, but why does the next command still say docker_torchserve cannot be found, I hope you can help me again to see if there is another solution, I'm doing this on windows and I've tried on ubuntu, but in the end I can't find docker_torchserve.

use command below for listing all of you local images  
```bash
docker images
```

I guess you should use this command  
```bash
docker run -d --name docker_torchserve -p 8080:8080 -p 8081:8081 qingweihe/docker_torchserve:latest
```
and maybe you will need to change another name  after `--name` parameter

**Comment by yxf1213** [comment]
> > > > 
> > > 
> > > 
> > > 您可以尝试在拉取图像之前登录到 docker hub
> > > ```shell
> > > docker login
> > > # enter you username and passwd
> > > ```
> > > 
> > > 
> > >     
> > >       
> > >     
> > > 
> > >       
> > >     
> > > 
> > >     
> > >   
> > > 如果没有docker hub账号，可以尝试在[docker中注册](https://www.docker.com/)
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/119831245/234481644-3d375bd5-0505-469c-a816-e40a943ec19c.png) I've logged into my docker hub account and run your command, and I see that it should have worked, but why does the next command still say docker_torchserve cannot be found, I hope you can help me again to see if there is another solution, I'm doing this on windows and I've tried on ubuntu, but in the end I can't find docker_torchserve.
> 
> use command below for listing all of you local images
> 
> ```shell
> docker images
> ```
> 
> I guess you should use this command
> 
> ```shell
> docker run -d --name docker_torchserve -p 8080:8080 -p 8081:8081 qingweihe/docker_torchserve:latest
> ```
> 
> and maybe you will need to change another name after `--name` parameter

Thank you very much, the problem has been solved, only the next command still reports an error, I have opened a new thread to see if there are partners who have encountered the same problem, thank you again!

**Comment by gptbert** [comment]
the paltform of docker image linux/arm64? not linux/amd64? why?

```bash
docker pull qingweihe/docker_torchserve
```

**Comment by hjessmith** [comment]
Because I developed this on a Macbook Pro with M1 chip.
