### ISSUE TITLE
Please provide model classes with weigths for drawn_humanoid_detector and drawn_humanoid_pose_estimator

### ISSUE THREAD

**Issue by VGFP** [facebookresearch/AnimatedDrawings#135]
Hi, 
please provide code and weights for drawn_humanoid_detector and drawn_humanoid_pose_estimator so they can be run without torchserve and can be exported to other formats like ONNX.
Thank you

**Comment by BoxFishLab** [comment]
also .want to provide pth, no need for torch server。
THANKS

**Comment by hjessmith** [comment]
The .mar files are just zip files containing model weights, handler code, config files, etc. Try unzipping them and see if what you need is there.
