### ISSUE TITLE
AssertionError: Error loading BVH: framenum - Animation Issue

### ISSUE THREAD

**Issue by SchmittFazed** [facebookresearch/AnimatedDrawings#140]
I'm having trouble using my own animation with any of the example drawings.

I've gone through the steps of creating an Animation in Rokoko.
Exported with the Mixamo preset - tried various settings within that.

I've made a new motion config with the correct path to the bvh file and the same end frame count.
I've tried using the mixamo_fff & fair1_ppf retarget files.
I have tried using the character shown in the example and the garlic drawing as well.

I feel like i've exhausted every possible solution and I still get this same error...

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\IKONIX-Desktop-2\AnimatedDrawings\animated_drawings\render.py", line 21, in start
    scene = Scene(cfg.scene)
  File "C:\Users\IKONIX-Desktop-2\AnimatedDrawings\animated_drawings\model\scene.py", line 30, in __init__
    ad = AnimatedDrawing(*each)
  File "C:\Users\IKONIX-Desktop-2\AnimatedDrawings\animated_drawings\model\animated_drawing.py", line 255, in __init__
    self._initialize_retargeter_bvh(motion_cfg, retarget_cfg)
  File "C:\Users\IKONIX-Desktop-2\AnimatedDrawings\animated_drawings\model\animated_drawing.py", line 317, in _initialize_retargeter_bvh
    self.retargeter = Retargeter(motion_cfg, retarget_cfg)
  File "C:\Users\IKONIX-Desktop-2\AnimatedDrawings\animated_drawings\model\retargeter.py", line 38, in __init__
    assert False, msg
AssertionError: Error loading BVH: framenum specified (559) and found (560) do not match

I noticed that in the example bvh files the Frame Time = 0.0333333 whereas my export = 0.011111
Is this possible the issue or have I missed something else??

Thank you

**Comment by yihleego** [comment]
Could you plz post the bvh?

**Comment by SchmittFazed** [comment]
[test.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11339045/test.zip)

**Comment by yihleego** [comment]
I modified the `Frames` of the `rokokoDance.bvh`: 559 -> 560
![image](https://user-images.githubusercontent.com/21337386/234746734-530e6e3b-5768-4432-ba7c-5bb50dc5ede1.png)
It works:
![image](https://user-images.githubusercontent.com/21337386/234747060-d86efaf2-1793-40c2-8dbf-3458e17b6287.png)

I have no idea why it was happening, please check the export settings of rokoko.

**Comment by SchmittFazed** [comment]
Lol... I tried 559, 558, 560 and none worked :o

**Comment by SchmittFazed** [comment]
Should i be running the render script from the animated drawings root folder?
Where the other files in the zip all correct?

**Comment by SchmittFazed** [comment]
from animated_drawings import render
render.start('./examples/config/mvc/test_mvc.yaml')

Is this the right command?

**Comment by yihleego** [comment]
Also remove `LeftInHandIndex` and `RightInHandIndex` from `mixamo_fff.xml`

**Comment by SchmittFazed** [comment]
Yeah, now i get this:

AnimatedDrawings\animated_drawings\model\quaternions.py:61: RuntimeWarning: invalid value encountered in divide
  self.qs = self.qs / np.expand_dims(np.sum(self.qs ** 2.0, axis=-1) ** 0.5, axis=-1)

**Comment by yihleego** [comment]
> Yeah, now i get this:
> 
> AnimatedDrawings\animated_drawings\model\quaternions.py:61: RuntimeWarning: invalid value encountered in divide self.qs = self.qs / np.expand_dims(np.sum(self.qs ** 2.0, axis=-1) ** 0.5, axis=-1)

Use `up: +y` instead of `up: +z`, because the BVH doesn't need to be rotated, See also: [Motion Config File](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md#motion-config-file)

```yaml
filepath: examples/bvh/rokoko/rokokoDance.bvh
start_frame_idx: 0
end_frame_idx: 559 
groundplane_joint: LeftFoot
forward_perp_joint_vectors:
  - - LeftShoulder
    - RightShoulder
  - - LeftUpLeg
    - RightUpLeg
scale: 0.025
up: +y
```

![image](https://user-images.githubusercontent.com/21337386/234750209-2ae2ef2e-4629-4090-93bc-add9cd7f7c3f.png)

**Comment by SchmittFazed** [comment]
Thank you for that, it fixed it :)

**Comment by hjessmith** [comment]
Your original error message was caused because, depending upon the export options chosen, Rokoko will insert a frame at the beginning of the motion clip with the skeleton's default pose. But it doesn't increment the `Frames:` count, resulting in an invalid BVH. By manually incrementing the `Frames:` value, as you did, you can restore it to a valid BVH.

**Comment by yiouyou** [comment]
@SchmittFazed @hjessmith How did you fix the Frames issue? What kind of export settings of Rokoko did you use? I tried many export option combinations and manually increment the Frames number in bvh file, but non works for me. Many Thanks!
