### ISSUE TITLE
Run python image_to_animation.py drawings/garlic.png garlic_out Error,  Have you encountered the same problem, please advise

### ISSUE THREAD

**Issue by yxf1213** [facebookresearch/AnimatedDrawings#141]
![image](https://user-images.githubusercontent.com/119831245/234748760-d59eb430-6d6e-4a62-8487-135abddc169d.png)

win10 system, I got an error after running the command from image to animation, can any of you help to solve it?

**Comment by yihleego** [comment]
https://github.com/facebookresearch/AnimatedDrawings/blob/ceda092a5da380569d6793ef974710e7cc9c7ec1/examples/image_to_annotations.py#L50-L52

Please make sure your `docker_torchserve` is running and the returned `resp.status_code` should be `2xx`.

You can add the following code for testing:
```python
if resp.status_code >= 300:
    print("Failed to get bounding box", resp)
    return None
```

**Comment by yxf1213** [comment]
> https://github.com/facebookresearch/AnimatedDrawings/blob/ceda092a5da380569d6793ef974710e7cc9c7ec1/examples/image_to_annotations.py#L50-L52
> 
> 请确保您`docker_torchserve`正在运行并返回的`resp.status_code`应是`2xx`。
> 
> 您可以添加以下代码进行测试：
> 
> ```python
> if resp.status_code >= 300:
>     print("Failed to get bounding box", resp)
>     return None
> ```

Thank you very much for your help, but because I am not familiar with docker and the program, I am a novice, I don't understand how to do what you mentioned, is there any similar documentation or can you tell me the steps to help me to solve this error, thank you very much.

**Comment by yihleego** [comment]
Oh I see, before you run `image_to_animation.py`, you have to run `TorchServe`. 
You can find the docs on the home page (the [README.md](https://github.com/facebookresearch/AnimatedDrawings/blob/main/README.md#animating-your-own-drawing))

----

![image](https://user-images.githubusercontent.com/21337386/234772923-fbcf4ae0-144a-4aef-ba4a-e2f04e09e848.png)

**Comment by yxf1213** [comment]
> 哦，我明白了，在你跑之前`image_to_animation.py`，你必须先跑`TorchServe`。 您可以在主页上找到文档（[README.md](https://github.com/facebookresearch/AnimatedDrawings/blob/main/README.md#animating-your-own-drawing)）
> 
> ![图像](https://user-images.githubusercontent.com/21337386/234772923-fbcf4ae0-144a-4aef-ba4a-e2f04e09e848.png)

The official command given keeps getting stuck at docker build here, I don't know if it's because of the network, but I used docker_torchserve provided by a partner and started it manually in docker, then ran curl http://localhost:8080/ping此命令是正确的, just in the next step I get an error when running python image_to_animation.py drawings/garlic.png garlic_out command. I don't know why
![image](https://user-images.githubusercontent.com/119831245/234774934-fbea7740-33e8-4479-acae-dc965993ce4b.png)
![image](https://user-images.githubusercontent.com/119831245/234775072-7349f163-1565-405b-b9f4-4b64dd6d6321.png)

**Comment by yihleego** [comment]
Is there any error log with `docker_torchserve`?

You can use the following command:
```bash
docker logs -f --tail=500 docker_torchserve
```

**Comment by yxf1213** [comment]
> Is there any error log with `docker_torchserve`?
> 
> You can use the following command:
> 
> ```shell
> docker logs -f --tail=500 docker_torchserve
> ```

/

**Comment by yxf1213** [comment]
> Is there any error log with `docker_torchserve`?
> 
> You can use the following command:
> 
> ```shell
> docker logs -f --tail=500 docker_torchserve
> ```
[docker_log.txt](https://github.com/facebookresearch/AnimatedDrawings/files/11340474/docker_log.txt)
This is the log I ran out, the content is rather long, if you have time then you can trouble to help me look at it, I really do not know these very well

**Comment by yihleego** [comment]
Oops, it seems that `docker_torchserve` can't run on WSL, #136 they got the same problem.

**Comment by yxf1213** [comment]
> 糟糕，似乎`docker_torchserve`无法在 WSL 上运行，#136他们遇到了同样的问题。

Thank you very much, I will take a good look first, thanks again
