### ISSUE TITLE
The settings of exporting BVH from Rokoko

### ISSUE THREAD

**Issue by yiouyou** [facebookresearch/AnimatedDrawings#144]
1) Attached is the settings of exporting BVH from Rokoko. I tried many options, but it always showed errors, like: 
```
CRITICAL:root:framenum specified (2311) and found (2312) do not match
CRITICAL:root:Error loading BVH: framenum specified (2311) and found (2312) do not match
Traceback (most recent call last):
  File "f:\animateddrawings\animated_drawings\model\retargeter.py", line 34, in __init__
    self.bvh = BVH.from_file(str(motion_cfg.bvh_p), motion_cfg.start_frame_idx, motion_cfg.end_frame_idx)
  File "f:\animateddrawings\animated_drawings\model\bvh.py", line 162, in from_file
    assert False, msg
AssertionError: framenum specified (2311) and found (2312) do not match
```
**What's the correct exporting settings?**
![image](https://user-images.githubusercontent.com/14249712/235101269-11d14012-dc0f-4b57-9c3a-de9bf5e28746.png)

2) Within the rokoko example, the "end_frame_idx" is null. I tried it with int number as well, but it stills shows up errors. **Need some help** to figure this out.
![image](https://user-images.githubusercontent.com/14249712/235102205-0ad43a02-b425-45a1-a6f9-5d8df89b590d.png)

**Thanks**~

**Comment by hjessmith** [comment]
Hi @yiouyou,

Your first issue is a copy of #140, please see answers there.

`end_frame_idx` is unrelated to your issue. But you can read about it's function here: 
https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md#motion-config-file
