### ISSUE TITLE
Would it be possible optimize the code for better GPU usage?

### ISSUE THREAD

**Issue by gwojtaszczyk-clipo** [facebookresearch/AnimatedDrawings#145]
Would it be possible optimize the code for better GPU usage? Add usage of libs like CuPy, cuCIM or other tweaks like Numba lib?

**Comment by hjessmith** [comment]
I'm sure it would. Unfortunately I don't have the cycles to do that. Feel free to submit a PR if you figure out some ways to speed things up.

**Comment by Ajaypawar02** [comment]
Do we need GPU to run this repo?

**Comment by hjessmith** [comment]
You should be able to run it without a dedicated GPU.

**Comment by gwojtaszczyk-clipo** [comment]
Thanks for the reply. Unfortunatelly as for now I'm too newbie to OpenGL and etc. to handle optimization myself. I read that CuPy may increase times but it would require more sophisticated changes than just replacing imports of numpy :)
