### ISSUE TITLE
Incorrect mapping files & no video outputs - Via Touchdesigner

### ISSUE THREAD

**Issue by SchmittFazed** [facebookresearch/AnimatedDrawings#148]
Hi again,

I've run into another wall I'm not sure how to solve...

For context, I have animated drawings running via Touchdesigner.  I'm calling the image_to_animations script when a new image is detected. The workflow is somewhat working.  I can use some of the example motions and my own custom rokoko motions as well. 

The issue I have now is when I'm trying to use side profile drawings and multiple arms.
I've directed the image_to_animation.py script to use the same retarget file and motion file as the example MVC files. (six_arms, four_legs etc) and I'm even using the same images from the examples.

I can see the files being created, reaching the point of video and failing - with no output. 

I've attached a zip with all of the files included.

Am I missing a step again - I thought altering the path to the retarget and motion files in the .py script would work - as it did with other trials?

When I run the example script for four legs and six arms via miniconda they still work as usual.

Thankyou in advance

[animation_2.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11379629/animation_2.zip)

**Comment by hjessmith** [comment]
Hi @SchmittFazed,

image_to_animation.py won't work with anything other than an image of a forward facing bipedal character with two arms. As I mention in the README, 'you can manually specify a different skeletons within the character config and modify the specified retarget config to support it.' Basically, you'll need to open the config files with a text editor and make your changes if you want to deviate from the standard bipedal character skeleton.

**Comment by SchmittFazed** [comment]
So I think i'm confused with that process....and how the examples of four legs and six arms work.

Because i'm taking images in real time and then calling the/a script to generate the config files.
Should I be making a copy of the image-to-animation and adjusting that so it creates different types of skeletons?

**Comment by hjessmith** [comment]
The models we released were trained to detect and identify skeleton joint positions for 2-arm, 2-leg biped characters only. So the scripts we provide won't be able to automatically animate quadrupeds or characters with six arms.
