### ISSUE TITLE
How to get motion.yaml and retarget.yaml from .bvh

### ISSUE THREAD

**Issue by xavierchan** [facebookresearch/AnimatedDrawings#152]
Now, i can create new animate by combine built-in config and custom char picture. But when i want to use the new motion from imported .bvh file. I'am going to get stuck with motion.yaml and retarget.yaml. Because i don't know how to create them event though have docs at examples/config/README.md. I don't know how to convert bvh to motion.yaml and retarget.yaml.

Maybe I'm a layman in animation. But i hope to offer the script can convert bvh to motion.yaml and retarget.yaml. Even if he's not perfect.

**Comment by yihleego** [comment]
Sadly, we can't, please see: https://github.com/facebookresearch/AnimatedDrawings/issues/101#issuecomment-1511949154

The API `/predictions/drawn_humanoid_pose_estimator` returns a fixed skeleton format, which contains the position and name of the joint.

The function of `retarget.yaml` is to bind the joints of **BVH** to the **standard** joints, so if the skeleton hierarchy and joint names are different in the BVH you downloaded from somewhere, you have to manually create the `retarget.xml`.

--- 

![image](https://user-images.githubusercontent.com/21337386/236659477-219c5162-7457-45e7-9390-7d9a155b514f.png)

**Comment by xavierchan** [comment]
> drawn_humanoid_pose_estimator

Oh, i'm very happy to hear your reply. I really didn't notice this.

At first I thought that the character configuration was standard, and only the conversion of motion and retarget needed to be completed.
I ignored the char_joint_bvh_joints_mapping in the retarget file, because there is too much content in the configuration like noise, so I can't figure out how some content relationships between several files translate.

Maybe what I need is a simple tutorial on the conversion of these files, otherwise handwriting motion and retarget is very difficult. Can you provide a demo tutorial to help us learn how to create basic motion and retarget with the .bvh file we have and char_cfg.yaml?

**Comment by yihleego** [comment]
I'm not good at this either XD

I think only the maintainers of this project are familiar with it now.
Here is the doc for creating motion and retarget configs, you can try though: [Character Config File](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md#retarget-config-file)

**Comment by hjessmith** [comment]
It's not a simple process, unfortunately. I would recommend reading the README file (linked above by @yihleego) and looking at the configuration files used in the  `Getting Started` examples to try and get a better understanding of how things are working.

If, after doing that, you have questions about specific things, I'd be happy to answer them for you. And please feel free to create the demo tutorial you wish existed, @xavierchan. Members of this community (myself included) would be very grateful.
