### ISSUE TITLE
generate .bvh

### ISSUE THREAD

**Issue by ARDUJS** [facebookresearch/AnimatedDrawings#153]
Is there an open source library that automatic capture of character action and generate the bvh file？

**Comment by threefoldo** [comment]
I tried, but even with manual retargeting, the animate is still out of control.

**Comment by ARDUJS** [comment]
> I tried, but even with manual retargeting, the animate is still out of control.

Can you tell me how you generate the bvh file

**Comment by hjessmith** [comment]
@ARDUJS what do you mean by 'automatically capture of character action'? What sort of character are you trying to get motion data from? 
If you mean a video of a person, you can generate a BVH file directly from a video using a product like Rokoko or Deepmotion.
If you mean a stylized cartoon clip or something similar, extracting good skeletal motion from it is, to my knowledge, still an open research question.

**Comment by d4rkc0de** [comment]
@hjessmith is there an open source library to generate the .BVH from a video ? Because the 2 platforms that you mentioned (Rokoko, Deepmotion) seems not to be free, also you cannot automate the process using these 2 platforms.

**Comment by hjessmith** [comment]
Sorry, I'm unaware of any open source solutions.

**Comment by yihleego** [comment]
> @hjessmith is there an open source library to generate the .BVH from a video ? Because the 2 platforms that you mentioned (Rokoko, Deepmotion) seems not to be free, also you cannot automate the process using these 2 platforms.

https://github.com/HW140701/VideoTo3dPoseAndBvh
https://github.com/KevinLTT/video2bvh

I found these, but I haven't run them successfully yet.

**Comment by d4rkc0de** [comment]
> > @hjessmith is there an open source library to generate the .BVH from a video ? Because the 2 platforms that you mentioned (Rokoko, Deepmotion) seems not to be free, also you cannot automate the process using these 2 platforms.
> 
> https://github.com/HW140701/VideoTo3dPoseAndBvh https://github.com/KevinLTT/video2bvh
> 
> I found these, but I haven't run them successfully yet.

Thanks I've already tried both, they don't seem that are working, if somebody was able to run them, please share.

**Comment by iconnoci** [comment]
Now I download the action from https://www.mixamo.com/, and then export bvh in blender. The action can basically be displayed but the effect is not good. It should be that the manual configuration is not understood correctly. Let’s continue to try.

**Comment by FrancescoSaverioZuppichini** [comment]
interested as well

**Comment by professorLea** [comment]
> If you mean a video of a person, you can generate a BVH file directly from a video using a product like Rokoko or Deepmotion.


I search the tutorial of Rokoko Studio， but still not able to find a way to import a video from my phone and export  a BVH file.. :(
i need to use all the Rokoko equipment to recording my motions, then i can export to BVH file.

is my understanding correct?

![CleanShot 2023-05-26 at 15 01 05](https://github.com/facebookresearch/AnimatedDrawings/assets/20817319/f7f8ed58-5af2-4f3d-8ed5-50e17737668e)

**Comment by hjessmith** [comment]
@professorLea take a look at this: https://www.rokoko.com/products/video
