### ISSUE TITLE
Same image but `bbox` results from `image_to_annotations` and demo are different?

### ISSUE THREAD

**Issue by yihleego** [facebookresearch/AnimatedDrawings#154]
I used the same image run with `image_to_annotations.py` and the [web demo](https://sketch.metademolab.com/), but the result from the web demo is bigger and looks better.

Did I miss something or does the API `/predictions/drawn_humanoid_detector` require args?

## image_to_annotations.py

```json
[
    {
        "class_name":"humanoid",
        "bbox":[
            227.16668701171875,
            171.42706298828125,
            499.19720458984375,
            526.5897216796875
        ],
        "score":0.9974969029426575
    }
]
```
![texture](https://user-images.githubusercontent.com/21337386/236717408-9168ab05-58f6-47ab-8b1f-f71ebffc7070.png)

## Demo (https://sketch.metademolab.com)
```json
{
    "x1": 192,
    "y1": 164,
    "x2": 529,
    "y2": 545
}
```

![image](https://user-images.githubusercontent.com/21337386/236717835-5b91d526-2f47-41cc-b1d7-8c12b1c5bc5c.png)

**Comment by hjessmith** [comment]
They're actually completely different models, so I'm not surprised to see that the results don't line up perfectly. The online demo model was trained several years ago, and the model weights released alongside the project were obtained via fine-tuning with data collected from the online demo.

If the returned detection is clipping the extremities of your character, this can result in very bad segmentations maps. If you want to be certain to avoid this, I would recommend you pad the detected bounding box (e.g. add 15 pixels to each side) and use that in the downstream segmentation and pose estimation steps.

**Comment by yihleego** [comment]
Thank you for providing this information, it's better with padding now. 😄
