### ISSUE TITLE
How to configure yaml files

### ISSUE THREAD

**Issue by zmh723** [facebookresearch/AnimatedDrawings#157]
I have now generated my own BVH file. How do I need to configure my yaml file to make it run properly? This problem has been a headache for me for a long time

**Comment by hjessmith** [comment]
Have you taken a look at [this](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md) readme? It contains that information. You can also look at the example .yaml files for guidance.

**Comment by zmh723** [comment]
I'm sorry to bother you. I have already read your readme file, but I didn't understand it. Can you teach me a production method to implement it

**Comment by hjessmith** [comment]
I'm happy to help, but the readme contents and example yaml files were my attempt to show users how to configure the yaml files. Are there specific questions or things you want further clarification on?

**Comment by DevinXiaoBai** [comment]
[dance.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11474851/dance.zip)
I am currently using the bvh file generated by Rokoko and the yaml file configured by me, but there are always error prompts when I run it. Can you help me check and point out the problem

**Comment by zmh723** [comment]
I am currently using the bvh file generated by Rokoko and the yaml file configured by me, but there are always error prompts when I run it. Can you help me check and point out the problem
[Uploading dance.zip…]()
