### ISSUE TITLE
GLSL 3.30 is not supported.

### ISSUE THREAD

**Issue by httzipdev** [facebookresearch/AnimatedDrawings#158]
I have a Cloud VPS with no GPU, When I complete the setup of all requirements and run test scripts with `"USE_MESA": True`, it returns this error: "error: GLSL 3.30 is not supported."
[
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/14134588/bcfebaf0-fbe1-4f17-a285-f43f115bc7ce)
](url)
After hours of research then I realized that Python needs GPU to render, is it right?

I've tested it on my local machine and it worked fine. But how can I deploy on the VPS or any solutions?

Thank you.

**Comment by yihleego** [comment]
No GPU required, and you have to install OSMesa (Mesa’s off-screen interface)

**Comment by httzipdev** [comment]
Thank you @yihleego . I mistakenly installed outside `conda`, after re-install:
`$ conda activate animated_drawings`
`$ conda install -c menpo osmes`
It's working now. But every time I need to run my command,`conda activate animated_drawings` is required, Can i use it outside the conda ?

**Comment by yihleego** [comment]
> Thank you @yihleego . I mistakenly installed outside `conda`, after re-install: `$ conda activate animated_drawings` `$ conda install -c menpo osmes` It's working now. But every time I need to run my command,`conda activate animated_drawings` is required, Can i use it outside the conda ?


I haven't tried it yet, I think it should be possible

**Comment by hjessmith** [comment]
Is there a reason you need to run it outside Conda? Activating a conda virtual environment that's already been set up isn't a particularly complicated or intensive thing to do.
