### ISSUE TITLE
Quick Start, Step 3 error: zsh: command not found: AnimatedDrawings

### ISSUE THREAD

**Issue by BaubleBridge** [facebookresearch/AnimatedDrawings#165]
Apologies if this is the wrong place to asking beginner questions. I'm having trouble getting past step 3 of the Quick Start guide.

Step 1, I enter :conda activate animated_drawings
(animated_drawings) USERNAME@COMPUTERNAME ~ % 

Step 2, I enter: cd /Users/USERNAME/AnimatedDrawings
(animated_drawings) USERNAME@COMPUTERNAME AnimatedDrawings % 

Step 3, I enter: AnimatedDrawings % python
zsh: command not found: AnimatedDrawings

Appreciate it if someone could point out what I'm getting wrong at this step.

**Comment by yihleego** [comment]
Try just entering `python`

**Comment by BaubleBridge** [comment]
Thank you 🫣
