### ISSUE TITLE
Frozen, $python "image_to_animation.py" output

### ISSUE THREAD

**Issue by xpat** [facebookresearch/AnimatedDrawings#168]
I'm just beginning to troubleshoot this.  The last two lines of a lot of output are as follows: 

```
import 'shlex' # <_frozen_importlib_external.SourceFileLoader object at 0x79b5ea14edf0>
import 'netrc' # <_frozen_importlib_external.SourceFileLoader object at 0x79b5ea14eb20>
```

I'm trying to figure out if it has to do with limited memory. I'm on a Chromebook with Linux and if I run $ cat /proc/meminfo:
output:
```
MemTotal:        6783096 kB
MemFree:          184392 kB
MemAvailable:     429436 kB
Buffers:              24 kB
Cached:          2184328 kB
SwapCached:            0 kB
Active:          1378408 kB
Inactive:        1362200 kB
Active(anon):    1101732 kB
Inactive(anon):  1218444 kB
Active(file):     276676 kB
...
```
or 

```$ free -g -h -t```
output
```
               total        used        free      shared  buff/cache   available
Mem:           6.5Gi       4.2Gi       120Mi       1.7Gi       2.2Gi       395Mi
Swap:             0B          0B          0B
Total:         6.5Gi       4.2Gi       120Mi
```

In case I'm barking up the wrong tree I wanted to open this as an issue.

**Comment by hjessmith** [comment]
I haven't seen any error outputs that end with the two lines you've copied, so I can't tell you for certain whether it's memory related or not. At what point in the process are you seeing these errors? What step is causing it?

**Comment by xpat** [comment]
It fails at this final step in the README.md: % python image_to_animation.py drawings/garlic.png garlic_out

>  With that set up, you can now go directly from image -> animation with a single command:

    (animated_drawings) torchserve % cd ../examples
    (animated_drawings) examples % python image_to_animation.py drawings/garlic.png garlic_out

**Comment by hjessmith** [comment]
Okay. That step incorporates a Docker container running Torchserve to provide detection and pose estimation predictions. That step is quite memory intenstive (I've been recommending allowing your Docker container to have 16gb or even 32 gb of memory), so it could indeed be a memory issue if you're using a chromebook with only 6.5 GB of memory total. 

Are you able to ping the torchserver and get a 'healthy' reply?

**Comment by xpat** [comment]
Yes, I was able to ping the torchserver and get the 'healthy' reply, just as indicated in the readme.  I saw the recommendation for 16gb of memory. I was encouraged by the 'healthy' output.  (At first, I got the 'curl: (52) Empty' reply but waited another 10 seconds, ran curl http://localhost:8080/ping and got the green light message.)

**Comment by hjessmith** [comment]
After you try to run the script and get the error messages, if you ping the server again do you still get the healthy reply?

**Comment by xpat** [comment]
I didn't think of that, so thanks.  Next time I get it running that's what I'll do.  The idea is that if it returns an error it means that the server crashed, right? If it returns 'health' again, might that mean that it's just taking a long time and not necessarily running out of memory?  I guess the question is how to determine whether the server's crashing and if not, what's going on. 

Meanwhile I'm going to give this a try on a cloud vm with more memory.

**Comment by xpat** [comment]
@hjessmith OK, I re-ran it all and got through the part that I was stuck at ... 

```
import 'shlex' # <_frozen_importlib_external.SourceFileLoader object at 0x79b5ea14edf0>
import 'netrc' # <_frozen_importlib_external.SourceFileLoader object at 0x79b5ea14eb20>
```
From another tab, I got the 'healthy' output after I ran 
```
curl http://localhost:8080/ping
```
The command terminated without an error and returned me to my prompt.  Unfortunately in the "garlic_out" folder there was just the initial image.png and nothing else.  Meanwhile, it seems that space gets eaten up and from 32GB available I go to 42GB full, no more linux disk space. I keep running out of space.

**Comment by xpat** [comment]
I ran it again, pinging the server two times, before and after and both times it returned a healthy response.  According to Docker Desktop it's in use so I assume that means it's running, plus with the 'healthy' output.  I ran it this last time without the verbose flags (still on my Chromebook), it finished quickly and returned the command line prompt.  But 
still in the garlic_out folder there's just the image.png file.

The output shows a bounding box error.  (I  won't open a new issue until I've run all this on a cloud vm, if I ever get that to work.)

```
/examples$ python image_to_animation.py drawings/garlic.png garlic_out
Traceback (most recent call last):
  File "image_to_animation.py", line 41, in <module>
    image_to_animation(img_fn, char_anno_dir, motion_cfg_fn, retarget_cfg_fn)
  File "image_to_animation.py", line 19, in image_to_animation
    image_to_annotations(img_fn, char_anno_dir)
  File "/home/patrouch/AnimatedDrawings/examples/image_to_annotations.py", line 53, in image_to_annotations
    raise Exception(f"Failed to get bounding box, please check if the 'docker_torchserve' is running and healthy, resp: {resp}")
Exception: Failed to get bounding box, please check if the 'docker_torchserve' is running and healthy, resp: <Response [500]>
```

**Comment by xpat** [comment]
I closed this since I was able to get it to work on a more powerful machine.
