### ISSUE TITLE
Customize the BVH redirection file, the result gif display is very wrong

### ISSUE THREAD

**Issue by iconnoci** [facebookresearch/AnimatedDrawings#170]
I exported BVH from the fbx file to use, and re-wrote two configuration files, but the result is very weird, I read https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config you wrote /README.md#motion-config-file, I feel that the configuration file is not wrong, but the result is wrong, I would like to ask you to see where there is a problem

[walk.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11523825/walk.zip)

**Comment by hjessmith** [comment]
What happens if you change the projection methods from the upper limbs and lower limbs from `frontal` to `sagittal`? Can you also please share the character-specific files (joint overlay and char_config.yaml), as well as a screen capture of the motion being perform by the original skeleton?

**Comment by iconnoci** [comment]
[bounding_box.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11537640/bounding_box.zip)
I have changed the projection method frontal, sagittal and pca, and all the files in garlic_out are compressed for you.
![屏幕截图 2023-05-23 071403](https://github.com/facebookresearch/AnimatedDrawings/assets/22522962/deb9d60e-f22c-42b6-ab4f-566b44eb7e25)

**Comment by iconnoci** [comment]
Thank you for your reply

**Comment by hjessmith** [comment]
Okay, I think the problem may lie within the BVH parsing code. Is it easy for you to export another BVH from the .fbx, one in which each joint (excluding the root) has only rotation channels and not the position channels? If so, that would be helpful before I start debugging

**Comment by iconnoci** [comment]
Sorry, I use blender to import fbx and then export bvh, blender exports bvh, there is no option to export only rotation information but not position information.

**Comment by iconnoci** [comment]
[walk2.zip](https://github.com/facebookresearch/AnimatedDrawings/files/11539662/walk2.zip)
Do you see if this fits your requirements? I deleted the position information of the animation frame by frame, and kept the position information of the hips.

**Comment by iconnoci** [comment]
good job it works
![video](https://github.com/facebookresearch/AnimatedDrawings/assets/22522962/b3702c53-b911-4b08-a910-d27e1cafb848)
