### ISSUE TITLE
How to customize the main area (cropping)?

### ISSUE THREAD

**Issue by RevelationCollection** [facebookresearch/AnimatedDrawings#171]
I tried the page demo on the official website of www.sketch.metademolab.com. After uploading an image, it allows me to customize the cropping. 
I want to customize the cropping area in my local project just like on the official website, but I don't know how to do it.

**Comment by RevelationCollection** [comment]
I I want to generate a skeleton position file "char_cfg.yaml" based on the specified texture.png. How can I customize the processing?

**Comment by hjessmith** [comment]
There is no code within this OS project to customize the cropping. Feel free to submit a PR if you end up creating one that would be helpful to other developers.

If you look at the code within annotation_to_animation.py, you'll see where the predicted bounding box is used to crop the image before saving it as texture.png and sending it to the skeleton pose estimation model. If you modify the bounding box prediction so it contains the contents of your desired `texture.png`, it will create the desired char_cfg.yaml for you.

**Comment by httzipdev** [comment]
@RevelationCollection You can take a look at `image_to_annotations.py` line 75
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/14134588/113007e7-280b-49ef-88bb-618465890096)
You can change it like this.

**Comment by RevelationCollection** [comment]
Thank you very much, I have solved my problem.
 I commented on the relevant code of automatically detecting characters in the image_to_annotations.py file and replaced it with the size of the box for the original image. 
So we only need to customize the bounding_box.yaml file. 

Thank you very much.


```
    # crop the image
    # cropped = img[t:b, l:r]
    # edit code -> custom size
    height, width = img.shape[:2]
    with open(str(outdir/'bounding_box.yaml'), 'w') as f:
        yaml.dump({
            'left': 0,
            'top': 0,
            'right': width,
            'bottom': height
        }, f)
    cropped = img
    
    # get segmentation mask
    mask = segment(cropped)
```
