### ISSUE TITLE
Can the windows system install animated_drawings?

### ISSUE THREAD

**Issue by leige666nb** [facebookresearch/AnimatedDrawings#172]
I use the git clone command, and then I can’t install animated_drawings with the pip command.

**Comment by leige666nb** [comment]
ERROR: Could not find a version that satisfies the requirement numpy==1.23.3 (from animated-drawings) (from versions: none)
ERROR: No matching distribution found for numpy==1.23.3

Why?

**Comment by leige666nb** [comment]
D:\anaconda\envs\Animated_Drawing\Library\bin\mkl_core.2.dll is not specified to run on Windows, or it contains errors. Please try to reinstall the program using the original ring. Or contact your system administrator or software vendor for support. Error status 0xc000007b.

**Comment by leige666nb** [comment]
Windows system can be used, the problem has been solved. Use git to clone the command first, and then install the dependent library with pip; conda may report an error when downloading the dependent library with pip, mine reported an error, and finally installed animated_drawings successfully using pip in the IDE.

**Comment by tigran-sargsyan-w** [comment]
> Windows system can be used, the problem has been solved. Use git to clone the command first, and then install the dependent library with pip; conda may report an error when downloading the dependent library with pip, mine reported an error, and finally installed animated_drawings successfully using pip in the IDE.

Can you write step-by-step instructions on how to use which tools(IDE) use to install it on Windows?
