### ISSUE TITLE
Created a Gradio UI

### ISSUE THREAD

**Issue by vensu-art** [facebookresearch/AnimatedDrawings#176]
Hi everyone,

I created a Gradio user interface to generate the mvc .yaml files.

I am very new to programming so have merci. Nonetheless, I believe it is quite useful tool, since it maintains the integrity of the original folder structure.

You basically just have to run the shell script and open the localhost link.
To utilize this tool, follow these simple steps:

1. Input the directory path to your AnimatedDrawings folder.
2. Specify your desired output directory for the generated .yaml file.
3. Click the "Refresh" button to populate the drop-down menus for Character, Motion, and Target. This action will populate these fields based on the folder names in the .../AnimatedDrawings/examples/characters directory for Characters, filenames in the .../AnimatedDrawings/config/motion directory for Motion, and filenames in the .../AnimatedDrawings/config/retarget directory for Target.
4. Next, select your preferred export option - file only, video, or GIF. Choosing MP4 will present a preview directly in the Gradio interface.
5. Finally, click "Export" to generate and export your MVC .yaml files.

I hope you have fun and an easier time using it. The next step will be the docker thing, but I have no idea how dockers work, so I will look into it. :D

I've submitted a pull request for this tool, but as this is my first attempt, I welcome any feedback or assistance. Meanwhile, feel free to explore the repository I've set up: https://github.com/vensu-art/AnimatedDrawingsGradio.

Have a nice day!

**Comment by hjessmith** [comment]
Hello @vensu-art,

Thank you for taking the time to make the project better :). If you wouldn't mind, can you add some tests to your code? Nothing complicated, but something to ensure that the configuration files it outputs are valid. This will be necessary to have before it is merged into main.

 I recommend using [pytest](https://docs.pytest.org/en/7.3.x/).

**Comment by vensu-art** [comment]
Sure! I will figure out how to do it, can't be that hard I guess :D

Thank you for the quick response @hjessmith

**Comment by hjessmith** [comment]
It'll be a valuable learning experience. Holler if you get stuck.

**Comment by aoyang-hd** [comment]
"I am having trouble writing. Could you please help me
/home/cv/.conda/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: Failed to open display localhost:13.0'
  warnings.warn(message, GLFWError)
/home/cv/.conda/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "<string>", line 3, in <module>
  File "/data/cv/aoyang/AnimatedDrawingsGradio/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
  File "/data/cv/aoyang/AnimatedDrawingsGradio/animated_drawings/view/view.py", line 47, in create_view
    return WindowView(view_cfg)
  File "/data/cv/aoyang/AnimatedDrawingsGradio/animated_drawings/view/window_view.py", line 34, in __init__
    self._create_window(*cfg.window_dimensions)  # pyright: ignore[reportGeneralTypeIssues]
  File "/data/cv/aoyang/AnimatedDrawingsGradio/animated_drawings/view/window_view.py", line 126, in _create_window
    logging.info(f'OpenGL Version: {GL.glGetString(GL.GL_VERSION).decode()}')  # pyright: ignore[reportGeneralTypeIssues]
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by vensu-art** [comment]
I am currently not at home, but can you give me a little bit more information on when the error occurred?
Does the repository work without using the Gradio UI by just following the commands mentioned in the readme? 
If it only happen when you use the Gradio UI, does it happen when you start the shell script or after you select the characters, motion, etc and start rendering it out?
