### ISSUE TITLE
Create retarget config file for the following running.bvh file 

### ISSUE THREAD

**Issue by Ajaypawar02** [facebookresearch/AnimatedDrawings#179]
HIERARCHY
ROOT Hips
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT LHipJoint
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT LeftHip
{
OFFSET 1.611894 -0.673180 -0.014919
CHANNELS 3 Zrotation Yrotation Xrotation
JOINT LeftKnee
{
OFFSET 0.014856 -0.000000 -7.518231
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT LeftAnkle
{
OFFSET 0.014554 -0.000000 -7.368488
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT LeftToe
{
OFFSET 0.001350 -2.102140 -0.681086
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
End Site
{
OFFSET 0.000000 -1.101390 0.000000
}
}
}
}
}
}
JOINT RHipJoint
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT RightHip
{
OFFSET -1.611894 -0.673180 -0.014919
CHANNELS 3 Zrotation Yrotation Xrotation
JOINT RightKnee
{
OFFSET -0.014856 -0.000000 -7.518231
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT RightAnkle
{
OFFSET -0.014554 -0.000000 -7.368488
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT RightToe
{
OFFSET -0.001350 -2.102140 -0.681086
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
End Site
{
OFFSET 0.000000 -1.101390 0.000000
}
}
}
}
}
}
JOINT lowerback
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT Chest
{
OFFSET -0.021080 0.169810 2.075730
CHANNELS 3 Zrotation Yrotation Xrotation
JOINT Chest2
{
OFFSET 0.050700 0.031410 2.084390
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT lowerneck
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT Neck
{
OFFSET -0.107310 -0.313700 1.604080
CHANNELS 3 Zrotation Yrotation Xrotation
JOINT Head
{
OFFSET 0.084110 0.308220 1.656790
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
End Site
{
OFFSET 0.039110 0.141460 1.691490
}
}
}
}
JOINT LeftCollar
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT LeftShoulder
{
OFFSET 2.210152 0.546940 0.732190
CHANNELS 3 Zrotation Xrotation Yrotation
JOINT LeftElbow
{
OFFSET 4.208010 -0.000001 0.067693
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
JOINT LeftWrist
{
OFFSET 4.447774 -0.000001 0.107699
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
JOINT lhand
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
JOINT LFingers
{
OFFSET 0.572473 -0.000000 -0.002868
CHANNELS 3 Zrotation Xrotation Yrotation
End Site
{
OFFSET 0.461535 0.000000 -0.002313
}
}
}
JOINT LThumb
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
End Site
{
OFFSET 0.468585 -0.468590 -0.002347
}
}
}
}
}
}
JOINT RightCollar
{
OFFSET 0.000000 0.000000 0.000000
CHANNELS 6 Xposition Yposition Zposition Zrotation Yrotation Xrotation
JOINT RightShoulder
{
OFFSET -2.269392 0.546940 0.732190
CHANNELS 3 Zrotation Xrotation Yrotation
JOINT RightElbow
{
OFFSET -4.208010 -0.000001 0.067693
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
JOINT RightWrist
{
OFFSET -4.447774 -0.000001 0.107699
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
JOINT rhand
{
OFFSET -0.100282 0.186255 0.019922
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
JOINT RFingers
{
OFFSET -0.731912 -0.000000 -0.065197
CHANNELS 3 Zrotation Xrotation Yrotation
End Site
{
OFFSET -0.590084 -0.000000 -0.052564
}
}
}
JOINT RThumb
{
OFFSET -0.100282 0.186255 0.019922
CHANNELS 6 Xposition Yposition Zposition Zrotation Xrotation Yrotation
End Site
{
OFFSET -0.599097 -0.601470 -0.053367
}
}
}
}
}
}
}
}
}
}
MOTION
Frames: 58
Frame Time: 0.033333

char_starting_location: [0.0, 0.0, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - RightShoulder
  - RightArm
  - RightForeArm
  - RightHand
  - RightHandEnd
  - LeftShoulder
  - LeftArm
  - LeftForeArm
  - LeftHand
  - LeftHandEnd
  method: pca
  name: Upper Limbs
- bvh_joint_names:
  - RightUpLeg
  - RightLeg
  - RightFoot
  - RightToeBase
  - LeftUpLeg
  - LeftLeg
  - LeftFoot
  - LeftToeBase
  method: pca
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Spine
  - Spine1
  - Spine2
  - Spine3
  - Neck
  - Head
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftHand
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - RightHand
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - LeftFoot
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - RightFoot
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightFoot
    - RightLeg
    - RightUpLeg
  - - LeftFoot
    - LeftLeg
    - LeftUpLeg
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: !!python/tuple
  - LeftArm
  - LeftForeArm
  left_foot: !!python/tuple
  - LeftLeg
  - LeftFoot
  left_hand: !!python/tuple
  - LeftForeArm
  - LeftHand
  left_knee: !!python/tuple
  - LeftUpLeg
  - LeftLeg
  torso: !!python/tuple
  - Hips
  - Spine3
  neck: !!python/tuple
  - Hips
  - Neck
  right_elbow: !!python/tuple
  - RightArm
  - RightForeArm
  right_foot: !!python/tuple
  - RightLeg
  - RightFoot
  right_hand: !!python/tuple
  - RightForeArm
  - RightHand
  right_knee: !!python/tuple
  - RightUpLeg
  - RightLeg
char_runtime_checks:
  - - above
    - neck
    - right_shoulder
    - left_shoulder

Here animation is moving side by side

**Comment by hjessmith** [comment]
You'll need to do this yourself. Use the readme:
https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md

Please only create issues for specific questions, ideally ones that other can benefit from.
