### ISSUE TITLE
New Animation from BVH file

### ISSUE THREAD

**Issue by samo8666** [facebookresearch/AnimatedDrawings#180]
Hello @hjessmith 
Nice to meet you!
We love your work samples, and we already tried to run all your animations here.
We are trying to make new animations like running, and we have .bvh file for them.
But new animation is not implementing well.
Could you please help us in new animation implementation?
Actually, we are doing one project from your work repo, and if you can help us in this, then we can pay you for your effort and help.
We need to implement the new animation quickly, so we want you to cooperate with us in this job.
If you let me know your contact email, then we can discuss more details.
Thank you!

**Comment by hjessmith** [comment]
May I ask why you need the animations implemented quickly? There are some internal review steps which I must go through to work outside my company.

Please provide me with your email and I will follow up.

**Comment by samo8666** [comment]
Thank you for your answer.
We think that you can implement good animations quickly.
Maybe, according to your availability, if you can implement 1 new animation/day, then it should be fine.
We have 3D modeling designer who made animations.
ad.samo8666@gmail.com

Please contact us via this email.

**Comment by hjessmith** [comment]
Sorry, I don't have the cycles to help you with something like that. If you have specific questions that the community can benefit from, feel free to open issues for them.

**Comment by Ajaypawar02** [comment]
Thank you for your help @hjessmith
