### ISSUE TITLE
New Animation Implementation

### ISSUE THREAD

**Issue by samo8666** [facebookresearch/AnimatedDrawings#181]
Hello @hjessmith 
We really need your help.
We could run all your current animations, and trying to make new animations.
We tried to make .bvh file and .yaml file, but new animation is not showing.
Could you please try to help us?
If you can help us, then we can pay directly for your effort and help including upfront.
We know that you are busy on company work, but please try to help others who are trying to make good projects from your idea.

Thank you!

**Comment by hjessmith** [comment]
My cycles are quite limited, and I'm trying to help as many people as I can with them. To that end, if there are specific problems you are having getting things working, please describe them here, including all relevant details, and I'll be happy to try and help you resolve them. Then others will be able to benefit from your questions and my answers.
