### ISSUE TITLE
Feature Request: GIF Import with Animation & Export of Joint Change Coordinates for 2D Animation

### ISSUE THREAD

**Issue by YanMednis** [facebookresearch/AnimatedDrawings#182]
Hello!

Firstly, I want to express my gratitude for the work you've done with this repository.

I have two inquiries that I hope you can assist me with:

1) GIF Import with Animation: I was wondering if it's possible to import a GIF file that includes animation instead of a PNG file. Specifically, I'd like the model to remain static, but with a minor additional animation (for instance, eye blinking). Could you provide some insight into the complexity of implementing this feature?

2) Joint Change Coordinates for 2D Animation: Is there a way to generate an auxiliary file containing the coordinates of joint changes for the output 2D animation? Essentially, I'd like for every frame's joint coordinates to be saved, similar to how the Character Config File stores the joints' coordinates of the input image. If this isn't readily available, could you advise which file in the program I might need to modify to add this functionality? My goal is to write a script that converts these obtained coordinates into an ANIM file for 2D animation in UNITY.

Thank you in advance for your time and attention to my message. I appreciate any help or direction you can provide.

**Comment by hjessmith** [comment]
Hello, 

Thanks for the kind words.

1. This seems like a heavy lift. Neither Animated gif inputs nor facial animations are currently supported. Adding such features would require a major rewrite of the project as it stands. I would suggest you look around for other tools that might be better suited to that task.

2. There's currently no way to do that. It could be added, but it wouldn't be an easy thing to do. Essentially what you want is the location of the character's joints in image space for each video frame. You can find the world position of each joint by calling [`get_chain_worldspace_positions`](https://github.com/facebookresearch/AnimatedDrawings/blob/1326ae027c7b4e963020188c3b4085fa5242b38e/animated_drawings/model/joint.py#LL26C21-L26C21) on the characters's [root joint](https://github.com/facebookresearch/AnimatedDrawings/blob/1326ae027c7b4e963020188c3b4085fa5242b38e/animated_drawings/model/animated_drawing.py#L94). You'll then need to get the position and orientation of the [camera](https://github.com/facebookresearch/AnimatedDrawings/blob/1326ae027c7b4e963020188c3b4085fa5242b38e/animated_drawings/view/window_view.py#LL31C16-L31C16). Using those pieces of information and the techniques described [here](https://www.scratchapixel.com/lessons/3d-basic-rendering/computing-pixel-coordinates-of-3d-point/mathematics-computing-2d-coordinates-of-3d-points.html), you can compute the pixel coordinate of each joint. Be warned, it's a tricky thing to do if you're a computer graphics novice.

**Comment by YanMednis** [comment]
Hello, thank you for your response. It isn't quite what I need. I need to save recent calculated coordinates for a 2D plane. Am I right in thinking that the final relative coordinates for a 2D plane are given by self.rig.get_joints_2D_positions() within animated_drawing.py? And if so, does it give the coordinates in the same order they're listed in the char_cfg.yaml file?

My current solution involves inserting a function (_save_joints) to save the coordinates after the update definition (in animated_drawing.py). Here's my approach:
`    def _save_joints(self):
        """
        This method saves joint positions to a CSV file.
        """
        # Assuming self.joints are np arrays or lists containing the data
        joint_data = self.rig.get_joints_2D_positions()  
        # Convert the data to pandas DataFrame and save it as csv
        df_joints = pd.DataFrame(joint_data, columns=['X', 'Y'])

        df_joints.to_csv('/home/AnimatedDrawings/joints.csv', mode='a', header=False, index=False)`

**Comment by hjessmith** [comment]
Yes, get_joints_2D_positions() should give you what you need. I'm not sure about the ordering though. But you can call self.rig.root_joint._get_chain_joint_names() to get the joint ordering.
