### ISSUE TITLE
Any ideas to make it a 2D-Game develop tool?

### ISSUE THREAD

**Issue by Einsphoton** [facebookresearch/AnimatedDrawings#183]
Hi there,
I am a game developer, seeing your project make me impressed. Any further plan to make it as a game animation tool which animate a pixel character and output serious PNGs.
Features like:
-Output PNGs
-Directly Video Mocap
-Machine Learning with Character Turning Round Animation?

**Comment by hjessmith** [comment]
Hi Einsphoton,

Thanks for sharing your ideas. I've thought about these, but haven't started implementing any of them yet. For point 1, the output pngs, are you referring to a sprite sheet or something similar?

**Comment by Einsphoton** [comment]
> Hi Einsphoton,
> 
> Thanks for sharing your ideas. I've thought about these, but haven't started implementing any of them yet. For point 1, the output pngs, are you referring to a sprite sheet or something similar?

Yes, it is exactly what I want. And further more, I have been searching a tool like that for a long time. What if there is a tool which I can create my own pixel character(8 directions) and animate them with multiply prompts that would be the cooleset thing in game industry.
