### ISSUE TITLE
What would happen if I modify the spacing of the mesh, and remove BFS for finding and nearest joint bones?

### ISSUE THREAD

**Issue by yihleego** [facebookresearch/AnimatedDrawings#184]
Hello Jesse,

I'm trying to figure out the time-consuming parts of the project, I found several functions and modified them。

It seems that the exported video has not changed, so I wonder what would happen if they are modified?

--- 

Modified the `num` of `np.linspace` to `20`:

https://github.com/facebookresearch/AnimatedDrawings/blob/1326ae027c7b4e963020188c3b4085fa5242b38e/animated_drawings/model/animated_drawing.py#L551-L554

```python
 _x = np.linspace(0, self.img_dim, 20) 
 _y = np.linspace(0, self.img_dim, 20) 
```

And removed the BFS search:

https://github.com/facebookresearch/AnimatedDrawings/blob/1326ae027c7b4e963020188c3b4085fa5242b38e/animated_drawings/model/animated_drawing.py#L439-L460

--- 

CPU: Intel Core i7-9700K
Memory: 32 GiB

Before:

Finished _generate_mesh in 5.325196027755737 seconds
Finished _initialize_joint_to_triangles_dict in 4.546596050262451 seconds
Finished ARAP in 6.044237852096558 seconds

![video_1](https://github.com/facebookresearch/AnimatedDrawings/assets/21337386/e12beac9-0caa-4713-9954-cc47cc306e7c)

After:

Finished _generate_mesh in 4.3196210861206055 seconds
Finished _initialize_joint_to_triangles_dict in 0.08604288101196289 seconds
Finished ARAP in 3.5901248455047607 seconds

![video_2](https://github.com/facebookresearch/AnimatedDrawings/assets/21337386/ece572a4-dbec-4083-84c0-00acb0367475)

---

Thank you. Looking forward to your reply.

**Comment by hjessmith** [comment]
Hi @yihleego,

I encourage your efforts to speed things up. There are some visible differences between those two videos, though.

The BFS is done to map each triangle within the character mesh to a joint (or bone segment) within the character's rig. Essentially, it creates a coarse part-level segmentation of the character's 'left upper arm', 'left lower arm', 'right upper arm ', 'torso', etc. 

Once we have this mapping, we can using the driving motion data to determine e.g. whether the character's 'left lower arm' should be rendered in front of or behind its 'torso'. This gives the illusion that the character is moving in '2.5D' space. 

Without the mapping, the triangles of the character's mesh are instead rendered in whatever order the mesh generation algorithm created them in. You can actually see this in your second video:  the character's lower arms overlap with the torso (at the bottom of the jumping jack)- the upper arm is rendered on top of the toros, but parts of the lower arms are rendered below the torso and therefore aren't visible.

The effect isn't too bad for this particular motion/character combo, but for other combinations where there's more overlap between body parts the effect would be much more pronounced.

**Comment by hjessmith** [comment]
Your first change seems fine though. I don't think that will cause issues.

**Comment by yihleego** [comment]
Thank you so much for the clear and insightful response. Have a nice day!😄

**Comment by hjessmith** [comment]
Hi @yihleego,

From your questions and helpful issue answers here in the repo, it's clear you've spent a lot of time developing with the Animated Drawings code. I am curious what you are creating- is it something that is publicly accessible?

**Comment by yihleego** [comment]
Hello @hjessmith,

This project is so cool, I want to add it to my personal project, but I have no powerful VMs, so I'm trying to figure out how to reduce the cost.

And I don't have much work in these few months, so I have free time to study with the Animated Drawings. 😄

**Comment by hjessmith** [comment]
I see. Well I am happy to hear that you like the project and enjoy looking for ways to optimize it. 

If you are ever in the SF Bay Area, let me know. I'll buy you some coffee as a thank you for all the issue answers you've been supplying 🙂👍
