### ISSUE TITLE
Possible to get the animated gif's from https://sketch.metademolab.com/canvas

### ISSUE THREAD

**Issue by Manicipal** [facebookresearch/AnimatedDrawings#185]
Hey Jesse

I really love what you've made here! Honestly made me smile when first playing with it! I'm making a free (funded by myself) app for children to support learning to draw. I'm working on integrating your work in our next mile stone. To save time is it possible to get the animated gif's from step 4 in the upload process on [](https://sketch.metademolab.com/canvas) ? I'd like to offer users a similar web experience to select the animation from the list.

Cheers
Paul

**Comment by Manicipal** [comment]
Links missing! https://sketch.metademolab.com/canvas[https://sketch.metademolab.com/canvas](url)

**Comment by hjessmith** [comment]
Hi Paul,

Glad you like the project. Most of the animations used to create the motions within the browser based demo are from Mixamo. Due to the TOS I can't reshare the data, but you can download them from Mixamo yourself.

**Comment by jumpjack** [comment]
I think the point is: rather than exporting in .mp4 format, export in .gif format.
