### ISSUE TITLE
bvh without the use of rococo

### ISSUE THREAD

**Issue by iigordyachenko** [facebookresearch/AnimatedDrawings#187]
Thank you very much for sharing this model!
For me it was a real challenge to automate the whole animation process without using rococo, but I did it)

**Comment by iigordyachenko** [comment]
open source solutions are used to create bvh files

**Comment by d4rkc0de** [comment]
@iigordyachenko  Can you share the open source solutions you are using ?

**Comment by iigordyachenko** [comment]
> @iigordyachenko Можете ли вы поделиться решениями с открытым исходным кодом, которые вы используете?

AlphaPose+MotionBERT+video2bvh

I will try to post my code within 7-14 days.

**Comment by ayonmollah** [comment]
Hello there, Can I use Hand Made animations (Key Frame Animations) to work with it? Mainly I am a 3D Artist so I can do so much clean Animations but Don't know why Is it not working.

**Comment by hjessmith** [comment]
You can @ayonmollah, but you'd need to convert them into BVH formation and ensure the skeleton joint names are properly reflected in the motion_cfg and retarget_cfg files.

**Comment by ayonmollah** [comment]
I did but While I do the Animation with Blender it always messes up the
Animation. It never gets perfect

**Comment by yujinqiu** [comment]
@iigordyachenko Is there any update ?

**Comment by fabiocat93** [comment]
any news?

**Comment by ayonmollah** [comment]
No, nothing yet.

**Comment by JinwooMcLee** [comment]
@iigordyachenko Hi, I'm wondering whether this repo is for making bvh without the use of rococo.
https://github.com/iigordyachenko/animated_all

If so, would you explain the code a bit or add a README to it?

**Comment by iigordyachenko** [comment]
Hello everyone! I would be happy to share my final solution, but unfortunately, it is very time-consuming to rewrite the current solution into a structured and readable format. At this stage, it's very messy code that I wouldn't want to show anyone. I'm gradually rewriting it into a more readable version, but it will take some time. I can't provide a specific timeframe because last time I promised to do it within two weeks, and in reality, it took much longer.


In fact, all that is required from you is to combine the three types of models that I mentioned above.

**Comment by iAmIlluminati** [comment]
any update on this boss ??
