### ISSUE TITLE
Error loading BVH: Use of .. or absolute path in a resource path is not allowed on Windows

### ISSUE THREAD

**Issue by BoxingLiuPersonal** [facebookresearch/AnimatedDrawings#188]

**Comment by hjessmith** [comment]
If you'd like help, can you please provide more context about the error. A screenshot or paste of the call stack, the contents of your config file, etc.

**Comment by BoxingLiuPersonal** [comment]
I figured it out, I altered the code a little bit, but thanks!

**Comment by Yaffa16** [comment]
Can you please share how you fixed it? I am having the same errors
