### ISSUE TITLE
Issues with Animation Scaling on GIFs and Manual Background Cut-out

### ISSUE THREAD

**Issue by YanMednis** [facebookresearch/AnimatedDrawings#189]
Hello!

As I was utilizing the tool, I've encountered two additional issues that I need assistance with:

1) Animation Scaling on GIF Files: Is the animation scale on the GIF file solely adjusted in the Motion Config File? My challenge lies with a BVH where the animation is of climbing upwards, and it extends beyond the GIF screen along the Y-axis. No matter how I alter the 'scale' parameter in the Motion Config File, the character's scale remains unchanged. If the animation in the BVH file exceeds the screen along the X-axis, changing the WINDOW_DIMENSIONS size helps when the X-axis becomes longer than the Y-axis. However, the same approach—increasing the Y-axis length compared to the X-axis—doesn't seem to work when the animation extends beyond the GIF screen along the Y-axis. The animation scale remains unchanged relative to the Y-axis in this case.

2) Disabling Mask Usage: How can I disable the use of a mask? The thing is, I manually cut out the background as automatic cut-out doesn't perform perfectly. However, the program still requires a mask.png file for operation, which means I have to create it beforehand—resulting in extra work. Is there a way to circumvent this?

Thank you in advance for your time and any help or direction you can provide with these issues.

**Comment by hjessmith** [comment]
Hello!

1. The 'scale' parameter adjusts the size of the BVH skeleton in the scene (which is mostly used for debugging purposes, and for most animation uses cases is never shown. To get the effect you're referring to, you'd want to reposition the camera further away from the character and adjust the size of the resulting video/gif.
2. It needs a mask or something like it to work. I think that writing it to a file like mask.png is usually the easiest thing to do, but if this doesn't work for you you can add some custom code here to read the mask however you'd like:
https://github.com/facebookresearch/AnimatedDrawings/blob/1326ae027c7b4e963020188c3b4085fa5242b38e/animated_drawings/model/animated_drawing.py#LL234C56-L234C56

**Comment by YanMednis** [comment]
Thank you for your help!
