### ISSUE TITLE
Increase Dimension of GIF file

### ISSUE THREAD

**Issue by Ajaypawar02** [facebookresearch/AnimatedDrawings#190]
hello folks,
is it possible to increase the dimension of GIF 
As when i am creating multiple animations together it is not possible to locate all 3 or 4 animations as we need to give different location for different characters 
If there is any way 
please let me know 

Thank You

**Comment by YanMednis** [comment]
Hi. You can change the resolution of a gif file by adding the following code to the MVC Config File:
```
view:
  WINDOW_DIMENSIONS: [300, 400]
```
Here's an example MVC Config File:
https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/mvc/background_example.yaml

Here is a complete instruction about editing MVC Config File:
https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md

**Comment by Ajaypawar02** [comment]
Thank you 
Also ,is there any way to reduce the time for rendering

**Comment by httzipdev** [comment]
@Ajaypawar02 
Check my question #164
