### ISSUE TITLE
display error 

### ISSUE THREAD

**Issue by Ajaypawar02** [facebookresearch/AnimatedDrawings#194]
WARNING:py.warnings:/home/ubuntu/anaconda3/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)

WARNING:py.warnings:/home/ubuntu/anaconda3/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)

![image](https://github.com/facebookresearch/AnimatedDrawings/assets/65480235/84fe6529-24bb-4ec7-8175-14ece1e914d7)

**Comment by httzipdev** [comment]
@Ajaypawar02 Hello, can you share how to solve this? Thank you

**Comment by httzipdev** [comment]
Never mind, I've fixed it
