### ISSUE TITLE
Segmentation error (core dumped)

### ISSUE THREAD

**Issue by Ajaypawar02** [facebookresearch/AnimatedDrawings#196]
I am using Fastapi so whenever i am turning USE_MESA=True 
i am getting this error as segmentation error (core dumped) .
can anyone tell why is this error ??

**Comment by yihleego** [comment]
This issue is fixed, please pull the latest code.
See: https://github.com/facebookresearch/AnimatedDrawings/pull/177

**Comment by Ajaypawar02** [comment]
yes its working now
Thank You
