### ISSUE TITLE
Connection Error on Creating Animation

### ISSUE THREAD

**Issue by Anthot44** [facebookresearch/AnimatedDrawings#197]
Hello,

For the past three days I have been trying to create animations from my own drawings but to no avail. The constant headache has proved to be a connection error on the last step on the setup process:

`python image_to_animation.py drawings/garlic.png garlic_out`

I initially ran through the installation commands in Anaconda and have also tried in Ubuntu. With the following error:

![0hOBZ5apIk](https://github.com/facebookresearch/AnimatedDrawings/assets/84906434/88ae1776-e787-4b6c-adf1-774c94e3776a)

I have also tried installing the packages suggested from this post but this has proved to be no help either:
![chrome_HIWZ1XdoMw](https://github.com/facebookresearch/AnimatedDrawings/assets/84906434/4a95d79e-e272-4109-bf81-d6012005c08b)

If anyone has any ideas or solutions I would be most grateful.

**Comment by hjessmith** [comment]
What about after you've run `python image_to_animation.py drawings/garlic.png garlic_out`? If you ping the server again at that point, what response does it give?

**Comment by Anthot44** [comment]
> What about after you've run `python image_to_animation.py drawings/garlic.png garlic_out`? If you ping the server again at that point, what response does it give?

ah thankyou I havn't tried that, I'll give that a go later and get back to you

**Comment by hjessmith** [comment]
What sort of a machine are you running it on? If the Docker container doesn't have enough RAM (16gb, maybe 32gb....) Torchserve can die suddenly when you try to query it. Try giving it more RAM and see if that helps

**Comment by hjessmith** [comment]
See #105

**Comment by yihleego** [comment]
Hello guys, I found that if `docker_torchserve` runs in a CPU to memory ratio of 1:1 env, it will get stuck and consume all CPU and memory. I think it is caused by [torchserve](https://github.com/pytorch/serve) self. 

I tested the following cases:
| VM | Result | |
|:---:|:---:|:---:|
|2c4g|✅| slow but works |
|4c8g|✅| bbox: about 10s |
|8c16g|✅| bbox: about 3s |
|16c32g|✅| bbox: about 1s |
|4c4g|❌| stuck |
|8c8g|❌| stuck |
|8c10g|❌| stuck |
|16c16g|❌| stuck |

BTW, `docker_torchserve` works well on my 2c4g dev env. 🤣

```shell
docker run --cpus 2 -m 4g -d --name docker_torchserve -p 8080:8080 -p 8081:8081 docker_torchserve
````

**Comment by benjaminbojko** [comment]
Can confirm that running with `docker run --cpus 2 -m 4g -d --name docker_torchserve -p 8080:8080 -p 8081:8081 docker_torchserve` also resolves the issue for me. Ran on Win 11 with an Intel i9, 32GB RAM, 12 GB RTX 3080ti.

**Comment by thhung** [comment]
On mac I have to increase the memory to 13GB to fix this issue. Why does it take so much more memory than win 11 on mac?
