### ISSUE TITLE
Four-legged model?

### ISSUE THREAD

**Issue by nopjia** [facebookresearch/AnimatedDrawings#199]
> All of the example animations above depict "human-like" characters; they have two arms and two legs. Our method is primarily designed with these human-like characters in mind, and the provided pose estimation model assumes a human-like skeleton is present. But you can manually specify a different skeletons within the character config and modify the specified retarget config to support it.

How did you produce the walking pig? Do you also have a four-legged detector and pose estimator model? If so, is it available?

![](https://user-images.githubusercontent.com/6675724/223585043-7ce9eac0-bb4c-4547-b038-c63ca2852ef2.gif)

**Comment by hjessmith** [comment]
No, I created that character_cfg.yaml file by hand, unfortunately.
