### ISSUE TITLE
How do i create motion config from Mixamo fbx. 

### ISSUE THREAD

**Issue by Yaffa16** [facebookresearch/AnimatedDrawings#200]
I have generated the bvh from the mixamo fbx using Blender. However, I am unable to understand how to create the motion config and retarget file for this? Can I use any of the existing retaget config for Moxamo skeletons?

I when i use the retarget filr mixamo_fff.yaml and a config file pointing to the mixamo bvh, I get this error

AssertionError: Could not find BVH joint with name: None

**Comment by yihleego** [comment]
Please try to remove all strings `mixamorig:` in the BVH files.

![image](https://github.com/facebookresearch/AnimatedDrawings/assets/21337386/85f14ba2-c446-421a-a478-50cec9bdccf0)

There is a doc ([Retarget Config File](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md#retarget-config-file)) you need to read before you start get started.

See also: https://github.com/facebookresearch/AnimatedDrawings/issues/152#issuecomment-1537295160
