### ISSUE TITLE
Personalized BVH

### ISSUE THREAD

**Issue by ZhouWenbo-d** [facebookresearch/AnimatedDrawings#203]
Hi, I recentely downloaded the program and found it very fun to use and play with. However, when I tried to upload my own BVH file to increase the diversity of the animations, I ran into the problem of not having a correct retargetting file. My BVH file was generated using a video of me dancing and I used Rokoko studio as sugjested in the ReadMe file. Do I need to manually add a new motion file and a new  retargetting file, or is there a way to automate the process. Also, the BVH generated by Rokoko has a lot more bodyparts than the ones used in the original project. Thnaks.

**Comment by hjessmith** [comment]
You'll likely need to generate a new motion and retarget file, especially if the BVH generated by Rokoko is quite different from the ones in the examples I provide.

There have been a lot of questions asked here about how to get Rokoko outputs that work for this project. It may be useful for you to look at some of them (e.g. #152 )
