### ISSUE TITLE
Getting RIghtArm is not listed when selecting new motion

### ISSUE THREAD

**Issue by TadewosBell** [facebookresearch/AnimatedDrawings#206]
Hey,

I am getting the following error when running new motions on already annotated characters:

    joints_idxs = [self.bvh_joint_names.index(joint_name) for joint_name in joint_names]
ValueError: 'RightArm' is not in list

This was not an issue with the Dab bvh, why is it causing an error with the other selected motion and how can I solve this error?

thank you for the support and this cool tool!

**Comment by hjessmith** [comment]
Hello TadewosBell, 

See #133.

I'm closing this issue, but feel free to reopen if those comments don't solve your problem.
