### ISSUE TITLE
mac（m1)docker    pip install mmpose==0.29.0" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by cyfyv** [facebookresearch/AnimatedDrawings#210]
你好我配置docker一直报错
![9750e53daa9a8f0031240b8f9a47c7c2](https://github.com/facebookresearch/AnimatedDrawings/assets/53050306/46773172-0ada-477a-ab37-5850357010a7)

**Comment by zaixia2008** [comment]
您好 请问是怎么解决的  我也遇到同样的问题

**Comment by gaoshangle** [comment]
您好 请问解决了吗

**Comment by cyfyv** [comment]
没有等待大神解答
