### ISSUE TITLE
docker error

### ISSUE THREAD

**Issue by gaoshangle** [facebookresearch/AnimatedDrawings#211]
docker error

2077.1 Building wheels for collected packages: xtcocotools, chumpy
2077.1   Building wheel for xtcocotools (setup.py): started
2078.7   Building wheel for xtcocotools (setup.py): finished with status 'error'
2078.7   error: subprocess-exited-with-error
2078.7   
2078.7   × python setup.py bdist_wheel did not run successfully.
2078.7   │ exit code: 1
2078.7   ╰─> [27 lines of output]
2078.7       /opt/conda/lib/python3.11/site-packages/setuptools/installer.py:27: SetuptoolsDeprecationWarning: setuptools.installer is deprecated. Requirements should be satisfied by a PEP 517 installer.
2078.7         warnings.warn(
2078.7       running bdist_wheel
2078.7       running build
2078.7       running build_py
2078.7       creating build
2078.7       creating build/lib.linux-aarch64-3.11
2078.7       creating build/lib.linux-aarch64-3.11/xtcocotools
2078.7       copying xtcocotools/version.py -> build/lib.linux-aarch64-3.11/xtcocotools
2078.7       copying xtcocotools/cocoeval.py -> build/lib.linux-aarch64-3.11/xtcocotools
2078.7       copying xtcocotools/coco.py -> build/lib.linux-aarch64-3.11/xtcocotools
2078.7       copying xtcocotools/mask.py -> build/lib.linux-aarch64-3.11/xtcocotools
2078.7       copying xtcocotools/__init__.py -> build/lib.linux-aarch64-3.11/xtcocotools
2078.7       running build_ext
2078.7       Compiling xtcocotools/_mask.pyx because it changed.
2078.7       [1/1] Cythonizing xtcocotools/_mask.pyx
2078.7       /tmp/pip-install-elsb2ev5/xtcocotools_28eb54a6abd74c02a98f8591db55404c/.eggs/Cython-3.0.0-py3.11-linux-aarch64.egg/Cython/Compiler/Main.py:381: FutureWarning: Cython directive 'language_level' not set, using '3str' for now (Py3). This has changed from earlier releases! File: /tmp/pip-install-elsb2ev5/xtcocotools_28eb54a6abd74c02a98f8591db55404c/xtcocotools/_mask.pyx
2078.7         tree = Parsing.p_module(s, pxd, full_module_name)
2078.7       creating build/common
2078.7       creating build/temp.linux-aarch64-3.11
2078.7       creating build/temp.linux-aarch64-3.11/common
2078.7       creating build/temp.linux-aarch64-3.11/xtcocotools
2078.7       gcc -pthread -B /opt/conda/compiler_compat -Wsign-compare -DNDEBUG -fwrapv -O3 -Wall -fPIC -O3 -isystem /opt/conda/include -fPIC -O3 -isystem /opt/conda/include -fPIC -I/opt/conda/lib/python3.11/site-packages/numpy/core/include -I./common -I/opt/conda/include/python3.11 -c ../common/maskApi.c -o build/temp.linux-aarch64-3.11/../common/maskApi.o
2078.7       gcc: error: ../common/maskApi.c: No such file or directory
2078.7       gcc: fatal error: no input files
2078.7       compilation terminated.
2078.7       error: command '/usr/bin/gcc' failed with exit code 1
2078.7       [end of output]
2078.7   
2078.7   note: This error originates from a subprocess, and is likely not a problem with pip.
2078.7   ERROR: Failed building wheel for xtcocotools
2078.7   Running setup.py clean for xtcocotools
2079.0   Building wheel for chumpy (setup.py): started
2079.3   Building wheel for chumpy (setup.py): finished with status 'done'
2079.3   Created wheel for chumpy: filename=chumpy-0.70-py3-none-any.whl size=58286 sha256=45d71cf580b2b4e33fb3d4467a96a756f65afbf4b388a4c8ac18e67333f3fa0d
2079.3   Stored in directory: /root/.cache/pip/wheels/91/96/31/3e16aa7084783b2e57a81bb9a7fa3598d32445a964b1692259
2079.3 Successfully built chumpy
2079.3 Failed to build xtcocotools
2079.3 ERROR: Could not build wheels for xtcocotools, which is required to install pyproject.toml-based projects
------
Dockerfile:24
--------------------
  22 |     RUN pip install torch
  23 |     RUN mim install mmcv-full==1.7.0
  24 | >>> RUN pip install mmpose==0.29.0
  25 |     RUN pip install mmdet==2.27.0
  26 |     RUN pip install torchserve
--------------------
ERROR: failed to solve: process "/bin/sh -c pip install mmpose==0.29.0" did not complete successfully: exit code: 1

**Comment by naughtyGitCat** [comment]
same error on win11

**Comment by hjessmith** [comment]
I believe I just fixed this issue, see 361a907. Please try again and let me know if you're still running into problems.

**Comment by sangbum-hub** [comment]
2023/08/23 mmpose insatll error issue updated
thanks i solved this problem

**Comment by gaoshangle** [comment]
> I believe I just fixed this issue, see [361a907](https://github.com/facebookresearch/AnimatedDrawings/commit/361a9079fe1b1cff2e58fc6321b67f98fcfe9699). Please try again and let me know if you're still running into problems.
thanks
