### ISSUE TITLE
Animated Drawings for GPU

### ISSUE THREAD

**Issue by pyDashNinja** [facebookresearch/AnimatedDrawings#214]
Hi, I would like to know how can I run this with GPU? because it is very slow and the demo website it works so fast. how to match that speed?

**Comment by httzipdev** [comment]
The answer from #130 is: Not yet
To speed things up:  #163 #164

**Comment by pyDashNinja** [comment]
yup I tried to remove frames first it was taking long now I have reduced time by 60%. which is still 20-30 seconds but website demo seems to be very fast I wonder if it running on GPU.

**Comment by hjessmith** [comment]
We did a bunch of optimizations for the demo, but the rendering with a GPU isn't one of them. We instead are using a cloud instance with a powerful CPU

**Comment by pyDashNinja** [comment]
oh! great. can you recommend CPU on cloud? what type of CPU we should use.

**Comment by hjessmith** [comment]
Sorry, I can't recommend which one you'll need. You should experiment with the different options until you find something that works for your requirements.
