### ISSUE TITLE
How to run Docker `docker_torchserve` on GPU?

### ISSUE THREAD

**Issue by httzipdev** [facebookresearch/AnimatedDrawings#215]
Hello,

How can I set up `docker_torchserve` running with full GPU on Linux?
I found the cmd from the official `PyTorch` https://pytorch.org/serve/use_cases.html. Or add `--gpus all` to Docker cmd
But it's still not working.
Did I miss something?

My device:
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/14134588/8a4d32a4-1925-4f8b-a154-30ca6b5fbc0a)

Thank you.

**Comment by hjessmith** [comment]
That's not something I can provide support for at the moment. But I would recommend that familiarize yourself with Torchserve and the .mar files which it serves. They are zip files, you can unzip them to see the model handlers and weights. You may need to modify the handler directly and rebuild the .mar file, or you may need to pass additional parameters to torchserve.

**Comment by httzipdev** [comment]
Thanks for your information.
