### ISSUE TITLE
Use Mesa not working in docker image

### ISSUE THREAD

**Issue by TadewosBell** [facebookresearch/AnimatedDrawings#218]
hey, I have a docker container running this library and it is not rendering the animation due to issues with open gl

I have set the view config to:
`USE_MESA: True`
I installed the mesa utilities with the following command in the docker file:

`RUN apt-get install -y libgl1-mesa-dev freeglut3-dev mesa-common-dev`

but I am getting the error:
`from OpenGL.raw.GL import _errors File "/usr/local/lib/python3.9/site-packages/OpenGL/raw/GL/_errors.py", line 4, in <module> _error_checker = _ErrorChecker( _p, _p.GL.glGetError ) AttributeError: 'NoneType' object has no attribute 'glGetError'`

is there something I am missing, maybe a neccessary version? I see the fillowing line in mesa_view.py:

```
os.environ['PYOPENGL_PLATFORM'] = "osmesa"
os.environ['MESA_GL_VERSION_OVERRIDE'] = "3.3"
from OpenGL import GL, osmesa

```
and I am wondering if I need to install those versions to get it functioning. Please let me know if you know the answer.

**Comment by yihleego** [comment]
You can try this, it works for me: 

Dockerfile
```dockerfile
FROM ubuntu:20.04

RUN apt-get clean
RUN apt-get update && \
    apt-get install --no-install-recommends -y \
    python3.8 python3-pip python3-setuptools \
    python3-opencv python3-numpy \
    libosmesa6-dev freeglut3-dev  \
    libglfw3-dev libgles2-mesa-dev \
    libosmesa6 \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
    ffmpeg libavcodec-extra \
    && rm -rf /var/lib/apt/lists/*

ENV PYOPENGL_PLATFORM=osmesa

WORKDIR /app

COPY . /app

RUN python3.8 -m pip install -U pip
RUN python3.8 -m pip install -r requirements.txt

CMD ["python3.8", "app.py"]

```

requirements.txt
```
scipy==1.9.3
scikit-image==0.19.3
scikit-learn==1.1.2
shapely==1.8.5.post1
Pillow==9.3.0
glfw==2.5.5
PyOpenGL==3.1.6
tqdm==4.64.1
PyYAML==6.0
```

**Comment by TadewosBell** [comment]
This worked thank you!
