### ISSUE TITLE
When make my own animated drawings gif file, two legs stick together. 

### ISSUE THREAD

**Issue by stellaluminary** [facebookresearch/AnimatedDrawings#219]
Hi! thank your remarkable works.

I've been working to make animated drawings with the character.
if bad predictions happen, i fixed as written in main page follows. 

[Original Character]
![image_c4_hr](https://github.com/facebookresearch/AnimatedDrawings/assets/43261434/0a930c0e-dbfe-40d4-b770-47c511edebf5)

However, when i make my own animated drawings gif file, the generated animated character's two legs stick together

[own Character with Dab Motion]
![video_c4_hr_dab1](https://github.com/facebookresearch/AnimatedDrawings/assets/43261434/c2e33735-c22f-4ffa-bf09-1d6a114ec0d2)

i think it's because of too close of legs distance in mask.

[own character mask]
![mask_c4_hr](https://github.com/facebookresearch/AnimatedDrawings/assets/43261434/7dd7189f-66c8-4c2f-8d65-9776a468df5b)

So i cut it out manually using Paint Tool like below. More space between legs. 

[Modified mask]
![mask_more space](https://github.com/facebookresearch/AnimatedDrawings/assets/43261434/5c7f1c79-9e09-4b25-8a44-60b974d4d31c)

[own Character with Dab Motion using modified mask]
![1_Upper_sagittal_Lower_frontal_codiny_video](https://github.com/facebookresearch/AnimatedDrawings/assets/43261434/1637177a-de2b-41d3-a118-d1e8ef027beb)

By using modified mask, the generated gif file seems more plausible to me. 

But the problem happen.
I cut the mask into a square shape, but as you can see, the created image is an O-shaped leg shape.

In this case, i want to make more natural shape of the character's leg motion gif file.

More padding explained issue 171 doesn't work at all.

I saw the hope in your demo which works fine like i wish.

How can i solve this problem?

if possible, i want to fix the ear parts also.

Thanks

**Comment by hjessmith** [comment]
Hi @stellaluminary 

Is the drawing transparent? I just downloaded the version you uploaded and got a fine animation, so I'm having trouble recreating your issue. The space between the two legs should be more than enough for them not to be sticking together, so something else is going on. If it is transparent, try removing the alpha layer and running it through again.
