### ISSUE TITLE
Question About Mask Rotation

### ISSUE THREAD

**Issue by Brian417-cup** [facebookresearch/AnimatedDrawings#220]
I noticed that you had a 90 degree rotation operation on the mask before doing the mask triangulation patch. 

https://github.com/facebookresearch/AnimatedDrawings/blob/c5c3bc70a4af9b470d3ad51078904ac91d922242/animated_drawings/model/animated_drawing.py#L498

And after I running your triangulation function, I found that if without this operation, it would not have obtained the correct result. I would like to know why this rotation operation is needed.

Here is initialization mask , my visualization results about rotation and withou rotation respectively:
![mask](https://github.com/facebookresearch/AnimatedDrawings/assets/72691001/1b74925b-8c24-4560-b38d-25b8d3c13135)
![rotate](https://github.com/facebookresearch/AnimatedDrawings/assets/72691001/1104d908-e547-4d49-b61f-dbaad3ac3fe3)
![wo_rotate](https://github.com/facebookresearch/AnimatedDrawings/assets/72691001/516726e1-c4af-4de6-9fa9-c9bc4602c9db)

**Comment by hjessmith** [comment]
Hello @Brian417-cup,

I'm not entirely sure I understand your question. As you've already shown with your examples, if we don't rotate the mask then the resulting mesh is incorrectly oriented. That seems like one answer to your question, but I assume it is not the one you are after.

Could you please give me a little more context on what you mean and why you are asking this question?

**Comment by Brian417-cup** [comment]
Okay, here are more details: regarding the triangulation process of the mask, I have separately take out the generated mesh function you provided: 
https://github.com/facebookresearch/AnimatedDrawings/blob/c5c3bc70a4af9b470d3ad51078904ac91d922242/animated_drawings/model/animated_drawing.py#L533

and use the visualization function you provided to visualize the triangulation.:
https://github.com/facebookresearch/AnimatedDrawings/blob/c5c3bc70a4af9b470d3ad51078904ac91d922242/animated_drawings/model/arap.py#L305

At the beginning, I didn't notice that the input mask needs to be rotated first and just make the input mask have same adjusted width and height. Therefore, I got was the incorrect result you saw above. Then, I find in your source code have a rotation operation above. 

I wonder if the necessity of rotation operation is due to a process that transposes the image again during the subsequent triangulation process.  Please forgive me for being a beginner in the field of graphics.

**Comment by hjessmith** [comment]
In the Animated Drawings visualization code, the second dimension (the 'y' in [x, y, z]) cartesian coordinates) of a point defines its height. But when reading in an image using cv2, the resulting matrix has dimensions [nrows, ncols, nchannels]. Since the 'height' of a pixel in the image is determined by it's row, this information is contained in the first dimension. 

IIRC, the rotation is necessary to account for the mismatch between these two representations.
