### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by aoyang-hd** [facebookresearch/AnimatedDrawings#221]
Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from animated_drawings import render
>>> render.start('./examples/config/mvc/export_mp4_example.yaml')
/home/cv/.conda/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: Failed to open display localhost:13.0'
  warnings.warn(message, GLFWError)
/home/cv/.conda/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/data/cv/aoyang/AnimatedDrawings/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
  File "/data/cv/aoyang/AnimatedDrawings/animated_drawings/view/view.py", line 47, in create_view
    return WindowView(view_cfg)
  File "/data/cv/aoyang/AnimatedDrawings/animated_drawings/view/window_view.py", line 34, in __init__
    self._create_window(*cfg.window_dimensions)  # pyright: ignore[reportGeneralTypeIssues]
  File "/data/cv/aoyang/AnimatedDrawings/animated_drawings/view/window_view.py", line 126, in _create_window
    logging.info(f'OpenGL Version: {GL.glGetString(GL.GL_VERSION).decode()}')  # pyright: ignore[reportGeneralTypeIssues]
AttributeError: 'NoneType' object has no attribute 'decode'

**Comment by yihleego** [comment]
See：
https://github.com/facebookresearch/AnimatedDrawings/issues/128
https://github.com/facebookresearch/AnimatedDrawings/issues/99#issue-1669192538

**Comment by aoyang-hd** [comment]
I have solve it 
https://github.com/facebookresearch/AnimatedDrawings/issues/99#issuecomment-1711021198

**Comment by JiepengTan** [comment]
open file  ./examples/annotations_to_animation.py
add one line code :
`'view': {'USE_MESA':True},  # use MESA for headless server`

in here
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/8347962/5606b064-bc12-4baa-bb58-164fee0605a9)
