### ISSUE TITLE
why do custom animations keep coming out whacky?

### ISSUE THREAD

**Issue by TadewosBell** [facebookresearch/AnimatedDrawings#222]
Hey guys,

Like the title says when I try to use custom animations, no mater what they just keep coming out whacky.
I have changed the retargeting files according to skeleton of the BVH, I have tried changing the projects method from frontal, to saggital or PCA for each body part group and tried multiple bvh files but this just keeps happening. Here is an example:

BVH Animation:

![Issue blender animation](https://github.com/facebookresearch/AnimatedDrawings/assets/17089624/695303e2-3d01-478e-986b-5725d9145d55)

Animation Produced:
![Whacky_Run](https://github.com/facebookresearch/AnimatedDrawings/assets/17089624/29c638d2-a036-4023-b00b-f57b5a3b7dda)

Retargeting file:

char_starting_location: [0.0, 0.0, -0.5]
bvh_projection_bodypart_groups:
- bvh_joint_names:
  - LeftArm
  - LeftForeArm
  - LeftHand
  - LeftFinger1Metacarpal
  - RightArm
  - RightForeArm
  - RightHand
  - RightFinger1Metacarpal
  method: frontal
  name: Upper Limbs
- bvh_joint_names:
  - LeftThigh
  - LeftShin
  - LeftToe
  - RightThigh
  - RightShin
  - RightToe
  method: frontal
  name: Lower Limbs
- bvh_joint_names:
  - Hips
  - Spine1
  - Spine2
  - Spine3
  - Spine4
  - Head
  - LeftShoulder
  - RightShoulder
  method: frontal
  name: Trunk
char_bodypart_groups:
- bvh_depth_drivers:
  - Hips
  char_joints:
  - right_shoulder
  - left_shoulder
  - right_hip
  - left_hip
  - hip
  - torso
  - neck
- bvh_depth_drivers:
  - LeftHand
  char_joints:
  - left_elbow
  - left_hand
- bvh_depth_drivers:
  - RightHand
  char_joints:
  - right_elbow
  - right_hand
- bvh_depth_drivers:
  - LeftToe
  char_joints:
  - left_knee
  - left_foot
- bvh_depth_drivers:
  - RightToe
  char_joints:
  - right_knee
  - right_foot
char_bvh_root_offset:
  bvh_projection_bodypart_group_for_offset: Lower Limbs
  bvh_joints:
  - - RightToe
    - RightShin
    - RightThigh
  - - LeftToe
    - LeftShin
    - LeftThigh
  char_joints:
  - - left_foot
    - left_knee
    - left_hip
  - - right_foot
    - right_knee
    - right_hip
char_joint_bvh_joints_mapping:
  left_elbow: [LeftArm, LeftForeArm]
  left_foot: [LeftShin, LeftToe]
  left_hand: [LeftForeArm, LeftHand]
  left_knee: [LeftThigh, LeftShin]
  torso: [Hips, Spine2]
  neck: [Hips, Head]
  right_elbow: [RightArm, RightForeArm]
  right_foot: [RightShin, RightToe]
  right_hand: [RightForeArm, RightHand]
  right_knee: [RightThigh, RightShin]
char_runtime_checks:
  - [above, neck, right_shoulder, left_shoulder]

LInk to the BVH File if that helps:
https://utoon-animator.s3.amazonaws.com/Issue/Walk.bvh

**Comment by hjessmith** [comment]
That doesn't look right (obviously). Can you share your MVC, retarget, motion cfg as well so I can test locally?

**Comment by TadewosBell** [comment]
yes, here they are.
Retarget: https://utoon-animator.s3.amazonaws.com/Issue/mixamo_fff_3.yaml
Motion: https://utoon-animator.s3.amazonaws.com/Issue/Walk.yaml
MVC: https://utoon-animator.s3.amazonaws.com/Issue/Walk_MVC.yaml

Thank you for being so responsive!  I am making a coloring book that comes with online games using this library.

**Comment by TadewosBell** [comment]
hey, was this sufficient. Are you having any issues debugging locally?

**Comment by hjessmith** [comment]
Love the idea of a coloring book with online games, that's genius. Please share it with me when it's ready, I'd love to try it with my kid.

Interesting to hear that having more than 100 frames causes the docker to shut down. Maybe try giving it more memory?

When trying to get your example working, I had to modify retarget.yaml, as config.py's input validation expects `char_joint_bvh_joints_mapping` to have tuples, not lists. See image, your retarget_cfg is on the left, and one of my example ones is on the right:

<img width="1251" alt="Screenshot 2023-09-08 at 11 26 18 AM" src="https://github.com/facebookresearch/AnimatedDrawings/assets/6675724/18e3d3be-3a0f-4ac7-a757-574f64e8110f">

Are you using the most recent version of AnimatedDrawings? Do a `git pull` to make sure you're up to date. I suspect you're using an older version of Animated Drawings because, when I try your example today, I got this super cute video. Nice work:
![jWDlrOGrWh_Walk](https://github.com/facebookresearch/AnimatedDrawings/assets/6675724/33a23ea5-52b5-456f-84a4-e0645d0b92df)

**Comment by TadewosBell** [comment]
I will definitely share. 
I tried giving it memory, I also tried dividing the work to generate multiple different smaller gifs then joining them. All works on my pc but then just breaks when on cloud run. I cant seem to find the issue at all. Any ideas on how to debug. 

when I read the yaml file from S3 it was throwing an error with those !python/tuple declarations. I did use the most recent version but I will redownload and try it with the original repository to see if it works. If it does work with that then there must be a mistake with changes I made.

**Comment by hjessmith** [comment]
Sorry, other than suggesting you check the Docker logs (which I assume you've already done) I don't have any idea on how to debug. 

I'm closing this issue for now. If you've still got issues after trying with the original repository, feel free to reopen.

**Comment by TadewosBell** [comment]
it was indeed an old version of the repo that I had that was causing the issue. Thanks.
