### ISSUE TITLE
How can I use my own BVH files

### ISSUE THREAD

**Issue by Satenderpal** [facebookresearch/AnimatedDrawings#225]
Currently I am downloaded some _BVH from CMU Graphics Lab Motion Capture Database_. But When I am trying to use. I am getting the different different errors with different BVH files. 
```
assert False, msg
AssertionError: Could not find BVH joint with name: LeftShoulder
```
What is the wrong i do ? or What is the wrong in BVH files ?
How can I used different different BVH files with different Characters ?

**Comment by ianbrickbod** [comment]
How I got it to work was by editing the model in blender and then exporting it. I loaded one of the example bvh files and my bvh and editted the bones names till the names matched, I also had to subdivide on of the spine bones to give me enough.

**Comment by hjessmith** [comment]
This is one way. The other way is to modify the BVH joint names that are used in the retarget config to match those in your BVH file.
