### ISSUE TITLE
AssertionError,use

### ISSUE THREAD

**Issue by KaiOuYang** [facebookresearch/AnimatedDrawings#226]
I encountered the following error when using the BVH file extracted by myself to drive the picture animation,  How can i solve the problem? 

![image](https://github.com/facebookresearch/AnimatedDrawings/assets/29744607/a5db93f0-a5f1-4487-b266-8e63ed025e2e)

**Comment by hjessmith** [comment]
Please share the BVH, motion config, and the retargeter config you are using when you get the error.

**Comment by hjessmith** [comment]
Closing for now. Feel free to share those config files if you're still running into this problem
