### ISSUE TITLE
Browser demo SSL certificates expired

### ISSUE THREAD

**Issue by tedcrimson** [facebookresearch/AnimatedDrawings#227]
Website demo isn't working. The SSL certificate needs to be updated.

![Screenshot_20231002-115830.png](https://github.com/facebookresearch/AnimatedDrawings/assets/12010706/4d39883a-c4f0-4c1a-b5fc-bcc68d572a80)

![Screenshot_20231002-115900.png](https://github.com/facebookresearch/AnimatedDrawings/assets/12010706/ac0596ba-5ff5-4a7e-b685-ec9b376307bf)

**Comment by hjessmith** [comment]
Certs have been updated. Thanks for letting us know.
