### ISSUE TITLE
tA2xA2 is singular. perturbing...

### ISSUE THREAD

**Issue by thhung** [facebookresearch/AnimatedDrawings#228]
Hello, 

I prepared my character with your guidance in README, and correct the skeleton. After that I run: 
```
python annotations_to_animation.py my_char_out
``` 
And we get: 
```
point [[0.41860464 0.15813954]] not inside or on edge of any triangle in mesh. Skipping it
point [[0.41860464 0.06046511]] not inside or on edge of any triangle in mesh. Skipping it
```
then, it "freezes" from there.

From the logs, I could see that it seems it is in the loop of ARAP class. The last log is on the title, which means [here](https://github.com/facebookresearch/AnimatedDrawings/blob/47957714b0f875ddc4613ec4c1448de04760f838/animated_drawings/model/arap.py#L162). 

Would you mind helping me understand what happens and how to solve it?

**Comment by hjessmith** [comment]
Does this only happen for a particular character? And if so, can you share the texture, mask, and joint overlay?

**Comment by thhung** [comment]
@hjessmith This is the only character that I tried. The mask is prepared by myself. 
![texture](https://github.com/facebookresearch/AnimatedDrawings/assets/25224297/e43a9d0b-96d4-4930-8565-f2bd8c75a349)

![mask](https://github.com/facebookresearch/AnimatedDrawings/assets/25224297/44b672ff-cc8d-4a6c-b8dc-34fd9498ff7f)

<img width="198" alt="overlay" src="https://github.com/facebookresearch/AnimatedDrawings/assets/25224297/a5d31991-dcdf-4f72-a876-69752b8e4de2">

**Comment by hjessmith** [comment]
I'm not from looking at it why that would fair. Can you please share the actual files so I can run it myself? Also, try adding a border of 1px black pixels around the mask. If that fixes it, there's likely a bug somewhere I should address. So please let me know the outcome.

**Comment by 809837709** [comment]
Same problem.There're four missing points in my own image when I use the mask fixed by myself. Is this a bug?
Here is my texture, mask, and joint overlay. Thanks!
![mask](https://github.com/facebookresearch/AnimatedDrawings/assets/39438068/fa114437-bd8e-441f-8785-7168129f18fa)
![texture](https://github.com/facebookresearch/AnimatedDrawings/assets/39438068/0526f810-bb49-41f9-aa7a-6bc82807ac30)
![joint_overlay](https://github.com/facebookresearch/AnimatedDrawings/assets/39438068/6c7cdf86-82db-4789-98b3-7b18f6275ab2)

**Comment by 809837709** [comment]
> I'm not from looking at it why that would fair. Can you please share the actual files so I can run it myself? Also, try adding a border of 1px black pixels around the mask. If that fixes it, there's likely a bug somewhere I should address. So please let me know the outcome.

This works for me!
