### ISSUE TITLE
Alternative of ARAP

### ISSUE THREAD

**Issue by thhung** [facebookresearch/AnimatedDrawings#229]
Hello, 
Do you know some alternatives for the ARAP algorithm? I would like to create some animation where the body of character is rigid, only hands, legs (and maybe face) are animated. Currently from my experience, it seems ARAP distorts the body, too. It makes the animation less desired.

**Comment by hjessmith** [comment]
What you are asking for is possible with ARAP by assigning different weights to different edges within the mesh, but it's non-trivial and this code is not set up to do that at the moment. 

If you're curious and want to learn more, you can read the original paper. Section 5.2 deals with your feature request exactly. Be warned, there's lots of math :) :
https://www-ui.is.s.u-tokyo.ac.jp/~takeo/papers/rigid.pdf
