### ISSUE TITLE
Animating characters with cmu bvh

### ISSUE THREAD

**Issue by lomaharshana** [facebookresearch/AnimatedDrawings#230]
I have a character that has correct mask and char_cfg. I am trying the cmu bvh animation with it. But it doesn't seem to work correctly. Even the jumping_jacks animation (different_bvh_skeleton_example.yaml) with the bundled characters shows the hands inwardly curved. Other bvh files from cmu have even more serious issues. Is there anyway this can be fixed?

Attaching character texture, mask and char_cfg (renamed with extension txt as github doesn't allow yaml) of my character.

[char_cfg.txt](https://github.com/facebookresearch/AnimatedDrawings/files/12803644/char_cfg.txt)
![mask](https://github.com/facebookresearch/AnimatedDrawings/assets/69755555/fcb9ce39-14b6-4bfa-a6c6-5fe5259d21ab)
![texture](https://github.com/facebookresearch/AnimatedDrawings/assets/69755555/f31904e0-d0b7-4572-9f16-0a9e648d3d38)

**Comment by thhung** [comment]
Would you mind sharing the video of this character's animation (the one that works)?

**Comment by lomaharshana** [comment]
Actually, you are right. None of the animations work properly with this character. I am giving here the best among all. Could you tell me what's wrong with this character?

![anim2d](https://github.com/facebookresearch/AnimatedDrawings/assets/69755555/371bd812-072b-41d3-80cb-b84d6a287c58)

**Comment by hjessmith** [comment]
Tell me exactly what it is about this animation that you feel is broken. The algorithm we present here is for animating simple children's drawings, and this character is pretty far from that.

**Comment by lomaharshana** [comment]
Yes, I understand. Was just trying to see if I could stretch it to use some more complicated characters and with the extensively available free cmu bvh files. 
Thank you so much for the great work! It's a fantastic tool and almost feels like magic with simple hand drawn characters. I had tried in the past animating 2d with 3d animation data myself and know what a difficult thing it is. Kudos to you and the team!
