### ISSUE TITLE
Possible to get more motion config files?

### ISSUE THREAD

**Issue by Manicipal** [facebookresearch/AnimatedDrawings#231]
Hey. We love this. We're making something completely Free non profit for children. Are you or anyone able to share the 30+ motion config files outside the 4 or so example ones?

**Comment by hjessmith** [comment]
Sorry, we don't have motion config files for the 30+ animations in the browser demo in a shareable format. You can generate them yourselves following the motion cfg / retarget cfg README instructions and getting the motion data from Mixamo directly, though.

**Comment by Manicipal** [comment]
Just reading through the requirements. Just double checking I'll need to record a video of an actor (probably myself) doing various motions and exporting to BHV files to do that right?

These are the right steps?
https://github.com/facebookresearch/AnimatedDrawings/tree/main#creating-your-own-bvh-files

**Comment by hjessmith** [comment]
That’s correct. If you have access to a motion capture lab you could use
that too. Or you could get an animator to generate some motions for you.
But at the end of the day, you’ll need the motion in BVH format.
