### ISSUE TITLE
I am brand new to docker and your project, I am getting this error do not know how to resolve. Can someone will help:Failed to connect to localhost port 8080 after 15 ms: Connection refused

### ISSUE THREAD

**Issue by surabhiHalloween** [facebookresearch/AnimatedDrawings#234]

**Comment by surabhiHalloween** [comment]
I am brand new to docker and your project, I am getting this error do not know how to resolve. Can someone will help:Failed to connect to localhost port 8080 after 15 ms: Connection refused #234

**Comment by hjessmith** [comment]
Sounds like either Torchserve or Docker is not starting/running when you try to query it. Do you get any error messages or warnings when following previous steps in the instructions?
