### ISSUE TITLE
Build docker_torchserve 

### ISSUE THREAD

**Issue by sonseungbeom** [facebookresearch/AnimatedDrawings#237]
I am installing on Ubuntu.
In Docker, use "docker build -t docker_torchserve ." I got an error when using mmcv-full.
So, I set the torch version to 1.13.0 and installed it.
Can you tell me which versions are in the dockerFile?

**Comment by hjessmith** [comment]
Hi @sonseungbeom 

The DockerFile is a human-readable text file, you can see the versions of the dependencies within it:
https://github.com/facebookresearch/AnimatedDrawings/blob/main/torchserve/Dockerfile

Please let me know if this doesn't answer you question.

**Comment by sonseungbeom** [comment]
Hi @hjessmith 

Thank you for your answer.
I built torch_serve in Ubuntu 18.0.. 
When mim install mmcv-full==1.7.0, 
the error occure ;
Building wheels for mmcv-full (setup.py) .. /
I tryed pip install torch==1.13.0 , then mmcv-full==1.7.0 was installed.

so,
Can you tell me the version of each module needed to run pytorch-server?

**Comment by sonseungbeom** [comment]
I changed the the install torch version in Dockfile

pip install torch==2.0.0
Then,
mim install mmcv-full==1.7.0 

No error occurs.
