### ISSUE TITLE
human-like figure detection and pose estimation model

### ISSUE THREAD

**Issue by LongJi12** [facebookresearch/AnimatedDrawings#238]
I would like to use the dataset you provided to train the human body detection model and pose estimation model used in the code. Can you provide code for these two models？

**Comment by hjessmith** [comment]
Hello @LongJi12. The models were trained using the OpenMMLab framework. If you download the .mar files and unzip them, you will find the config files OpenMMLab uses to specify model architecture.

**Comment by LongJi12** [comment]
I have successfully extracted the. mar file and reviewed the relevant model content, but I still have difficulties during training. The downloaded dataset does not include the 2500 manually selected image materials mentioned in the paper and similar training materials_ Size-180000_ Dev.json, train_ Size-180000_ Can you provide ?



At 2023-10-13 00:21:50, "hjessmith" ***@***.***> wrote:

Hello @LongJi12. The models were trained using the OpenMMLab framework. If you download the .mar files and unzip them, you will find the config files OpenMMLab uses to specify model architecture.

**Comment by hjessmith** [comment]
Let me look around for them. I no longer have access to the environment I used to train, so I'll have to look around for it. Are you attempting to compare against it as a baseline or benchmark?

**Comment by LongJi12** [comment]
> Let me look around for them. I no longer have access to the environment I used to train, so I'll have to look around for it. Are you attempting to compare against it as a baseline or benchmark?

I want to use it as a benchmark for comparison

**Comment by javier-pkg-mda** [comment]
@hjessmith Did you manage to get these datasets used by the demo? I'm getting way worse outcomes using just dataset given in this repo.

**Comment by hjessmith** [comment]
After several unsuccessful searches, I've concluded that the list of 2500 manually selected images used to generate the smaller dataset didn't survive the environment transfer. I was able to find an incomplete list of the manually selected images, however, which I'll link here. Hopefully that can be of some use: https://drive.google.com/file/d/17fXv9NithNiFmmn_UmbMvWvJNZYL8zXv/view?usp=sharing
