### ISSUE TITLE
ModuleNotFoundError: No module named 'animated_drawings'

### ISSUE THREAD

**Issue by ShahryarSaljoughi** [facebookresearch/AnimatedDrawings#241]
I'm following the instructions of this repository to run test the examples.  
I followed the instructions up to the [Animating Your Own Drawing](https://github.com/facebookresearch/AnimatedDrawings#animating-your-own-drawing) section where it runs:

```
(animated_drawings) torchserve % cd ../examples
(animated_drawings) examples % python image_to_animation.py drawings/garlic.png garlic_out
```

Now I get the following error:
```
Traceback (most recent call last):
  File "image_to_animation.py", line 6, in <module>
    from annotations_to_animation import annotations_to_animation
  File "D:\FamousGitHubRepos\AnimatedDrawings\examples\annotations_to_animation.py", line 5, in <module>
    import animated_drawings.render
ModuleNotFoundError: No module named 'animated_drawings'
```

What is wrong and how can it be fixed?

**Comment by hjessmith** [comment]
Looks like the `animated_drawings` module isn't installed in your `animated_drawings` conda environment. 

Try installing again and, making sure the `animated_drawings` virtual environment is active, run `pip install -e .` in the project home directory to install `animated_drawings`.
