### ISSUE TITLE
 Could not find encoder for codec_id=27, error: Encoder not found ;      ( ubuntu 18.04.   Miniconda)

### ISSUE THREAD

**Issue by Andy-Ren** [facebookresearch/AnimatedDrawings#249]
ideoWriter will write to /root/workspace/animated_drawings/video.mp4
Using codec avc1
[ERROR:0@12.350] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (2927) open Could not find encoder for codec_id=27, error: Encoder not found
[ERROR:0@12.350] global /io/opencv/modules/videoio/src/cap_ffmpeg_impl.hpp (3002) open VIDEOIO/FFMPEG: Failed to initialize VideoWriter

**Comment by hjessmith** [comment]
Your version of opencv/ffmpeg doesn't include avc1 code (likely due to licensing issues). Try these steps:

https://github.com/facebookresearch/AnimatedDrawings/issues/232
