### ISSUE TITLE
Same image different results (demo vs local)

### ISSUE THREAD

**Issue by javier-pkg-mda** [facebookresearch/AnimatedDrawings#254]
I'm using same image in demo ( https://sketch.metademolab.com/ ) and also running image_to_animation.py locally and I'm getting different results. I've noticed mask is not really well done when using it locally but mask in demo is way better. I've read that the trained AI that demo uses is little bit more trained that the dataset provided in this repository, is it possible to have the same trained AI in this repo than the one being used in demo please? It is just performs too much better.

**Comment by hjessmith** [comment]
Hi @javier-pkg-mda 

Can you share some images showing the demo and local predictions you are referring to? The keypoint model I've shared here was actually trained on substantially more data than the version used by the demo, so I'm interested to see the image you're referring to.

The masking method used in this repo is basically the same one used in the demo. It's not a model but an image processing algorithm.

**Comment by javier-pkg-mda** [comment]
Thanks for the quick comment @hjessmith. Here are the files:

Original image: 
![javi_test](https://github.com/facebookresearch/AnimatedDrawings/assets/82495401/0c513556-a27c-4eff-a102-acfcc97b44a4)

Then running image_to_animation.py gives following mask:

![mask](https://github.com/facebookresearch/AnimatedDrawings/assets/82495401/f0c0ab8d-a7da-4e64-a657-a2981c22b668)

joint_overlay:
![joint_overlay](https://github.com/facebookresearch/AnimatedDrawings/assets/82495401/9c89e379-6d11-44c4-8d9b-6c17849b8361)

animation:
![video](https://github.com/facebookresearch/AnimatedDrawings/assets/82495401/f7db0472-e133-4a19-89dd-d3bc22669c5a)


If you use same image in your online demo, results becomes way much better. Any idea why this is happening?

**Comment by hjessmith** [comment]
It looks like the bounding box prediction is cutting off part of the character, which is causing the image segmentation to fail. The easiest way to fix this would be to add some padding around the character in the original image. Try to make sure there's at least a 20 pixel buffer on each side. My guess is, if you do that, it should fix your issue.

**Comment by pingfai** [comment]
I want to know how to create joint_overlay by photoshop? I have problem with the docker.

**Comment by javier-pkg-mda** [comment]
@pingfai I think joint_overlay.png is only for human readable purpose, you can edit it on your own by two options as far as I know:

1. edit your char_cfg.yaml and add X and Y coordinates on every joint_point, you can get coordinates by opening the mask or texture in any image editor.
2. you can use the following command:
python fix_annotations.py path_to_folder_with_char_cfg.yaml
then it will launch a service on your localhost:5050, open it, move points and click save, it will save new coordinates on your char_cfg.yaml automatically

**Comment by pingfai** [comment]
thanks從我的iPhone傳送javier-pkg-mda ***@***.***>於2024年1月9日 18:12寫道：﻿
@pingfai I think joint_overlay.png is only for human readable purpose, you can edit it on your own by two options as far as I know:

edit your char_cfg.yaml and add X and Y coordinates on every joint_point, you can get coordinates by opening the mask or texture in any image editor.
you can use the following command:
python fix_annotations.py path_to_folder_with_char_cfg.yaml
then it will launch a service on your localhost:5050, open it, move points and click save, it will save new coordinates on your char_cfg.yaml automatically
