### ISSUE TITLE
I would like to ask if it is necessary to use docker

### ISSUE THREAD

**Issue by ransheng11** [facebookresearch/AnimatedDrawings#256]
Hello，thank you very much for your contribution to this amazing project.I want to make my own animation, but I followed the steps and referred to other issues still did not go on, is there a way without docker

**Comment by hjessmith** [comment]
Hello @ransheng11 

The Docker container is only required to get the character annotations (cropped bounding box and joint locations). You can make these yourself though. It would be a little tedious, but would avoid needing to use Docker for anything. Just open one of the example character_config.yaml files and have a look.

**Comment by ransheng11** [comment]
Ok, I see, I ended up using docker for my work and I was pleasantly surprised at how it turned out, thank you so much for this project, I love it so much.

**Comment by ransheng11** [comment]
Sorry about that, I have another question for you, I don't want to see the results in real time when I run it, where can I turn it off?

**Comment by javier-pkg-mda** [comment]
@ransheng11 if you mean the pop up window showing the animation, to make it headless do the following:

you should add this line in your mvc_cfg.yaml

```
view:
  USE_MESA: True
```

**Comment by ransheng11** [comment]
> @ransheng11 if you mean the pop up window showing the animation, to make it headless do the following:如果您指的是显示动画的弹出窗口，要使其无头，请执行以下操作：
> 
> you should add this line in your mvc_cfg.yaml您应该在 mvc_cfg.yaml 中添加此行
> 
> ```
> view:
>   USE_MESA: True
> ```

Thank you very much, never understood what headless meant, so here it is
