### ISSUE TITLE
Failed to build Docker

### ISSUE THREAD

**Issue by wills06** [facebookresearch/AnimatedDrawings#259]
Running: docker build -t docker_torchserve .Command compilation failed~

I checked all the logs and found that:
# This will install the latest Torch;
Run pip install torch
# The compatible Torch version is 1.13, which cannot be compiled;
RUN mim install mmcv-full==1.7.0
# This will update Torch to the latest version;
RUN pip install mmpose==0.29.0

I adjusted the above dependencies and successfully installed them.After running TorchServe, I found that the .py file in the drawn_humanoid_pose_estimator.mar model file did not work properly.

I hope to provide the latest Dockerfile file or update the drawn_humanoid_pose_estimator.mar model file, which will allow me to run TorchServe in Docker.

Looking forward to your reply.

**Comment by ShahryarSaljoughi** [comment]
Hi  
Check out this issue: #240   , I guess you have solved the same issue in a different way that ended in problems in runtime.  
Try out specifying the version of torch inside the Dockerfile instead:

    RUN pip install torch==2.0.0

I have tested this approach and works just fine. Let me know what you get.  

BTW, It would be helpful if you had given the exact problem with the `.mar` model file, and the (part of) logs of the `docker build` command you first faced.

**Comment by hjessmith** [comment]
merged PR #275, which addresses docker build issue
