### ISSUE TITLE
Source code of fixing bounding box missing

### ISSUE THREAD

**Issue by ShahryarSaljoughi** [facebookresearch/AnimatedDrawings#260]
Hi,

Hope you all are doing well.

In the demo, I noticed that I can fix the bounding box originally detected by the model, but the `fixer_app` does not include such functionality. In `fixer_app`, I can fix the detected joints via an appealing UI; however, the same functionality is not provided for fixing the bounding box.

Though this is not part of the core animating project, it would be good to have that feature within the repository too.

I would be glad to develop this part and have it merged into the repo if the maintainers consider it necessary.

**Comment by hjessmith** [comment]
Hello @ShahryarSaljoughi 

Thanks for offering to improve the repo in this manner. Extending the annotation fixing tool to include bounding box edits would indeed be useful and I would merge such a PR into main. Do note that changes to the bounding box would have downstream effects on the segmentation mask and the joint locations, so the PR would need to handle making such modifications as well.

**Comment by ShahryarSaljoughi** [comment]
Thank you.  
OK then I'm on it, I'll let you know when the PR is ready.
I'm new to open source contributions, I suppose I should close this issue as it has met its purpose, I'll open a new issue when the PR is ready.
