### ISSUE TITLE
ERROR: failed to solve: process "/bin/sh -c mim install mmcv-full==1.7.0" did not complete successfully: exit code: 1

### ISSUE THREAD

**Issue by gaurish1212** [facebookresearch/AnimatedDrawings#261]
when we build docker image then we get error if we change version of mmcv-full==1.7.2 then image build but animted gif not created we got another error

 Building wheels for collected packages: mmcv-full
17.88   Building wheel for mmcv-full (setup.py): started
23.98   Building wheel for mmcv-full (setup.py): finished with status 'error'
24.04   error: subprocess-exited-with-error
24.04
24.04   × python setup.py bdist_wheel did not run successfully.
24.04   │ exit code: 1
24.04   ╰─> [1342 lines of output]
24.04       Compiling mmcv._ext only with CPU
24.04       running bdist_wheel
24.04       /opt/conda/lib/python3.11/site-packages/torch/utils/cpp_extension.py:502: UserWarning: Attempted to use ninja as the BuildExtension backend but we could not find ninja.. Falling back to using the slow distutils backend.
24.04         warnings.warn(msg.format('we could not find ninja.'))
full_abbe77a315ed43f0b5eeb6dda6ebf436/mmcv/ops/csrc/common/pytorch_cpp_helper.hpp:3,
24.04                        from ./mmcv/ops/csrc/pytorch/active_rotated_filter.cpp:5:
24.04       /opt/conda/lib/python3.11/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h: In static member function ‘static Return c10::Dispatcher::callWithDispatchKeySlowPath(const c10::TypedOperatorHandle<Return(Args ...)>&, at::StepCallbacks&, c10::DispatchKeySet, const c10::KernelFunction&, Args ...)’:
24.04       /opt/conda/lib/python3.11/site-packages/torch/include/ATen/core/dispatch/Dispatcher.h:597:6: warning: ‘if constexpr’ only available with ‘-std=c++17’ or ‘-std=gnu++17’
24.04         597 |   if constexpr (num_boxed_args != 0) {
24.04             |      ^~~~~~~~~
24.04       error: command '/usr/bin/gcc' failed with exit code 1
24.04       [end of output]
24.04
24.04   note: This error originates from a subprocess, and is likely not a problem with pip.
24.04   ERROR: Failed building wheel for mmcv-full
24.04   Running setup.py clean for mmcv-full
25.41 Failed to build mmcv-full
25.41 ERROR: Could not build wheels for mmcv-full, which is required to install pyproject.toml-based projects
------
Dockerfile:23
--------------------
  21 |     RUN pip install openmim
  22 |     RUN pip install torch
  23 | >>> RUN mim install mmcv-full==1.7.0
  24 |     RUN pip install mmdet==2.27.0
  25 |     RUN pip install torchserve
--------------------

**Comment by lbj96347** [comment]
I just removed `1.7.0` and just install mmcv-full, everything runs well. My env is `ubuntu 22.04.3` 

Try: 

> RUN mim install mmcv-full

**Comment by hjessmith** [comment]
PR #275 resolved this
