### ISSUE TITLE
 Failed to get bounding box

### ISSUE THREAD

**Issue by gaurish1212** [facebookresearch/AnimatedDrawings#262]
Hy

When we build image after change version of mmsc-full==1.7.0 instaed mmcv-full==1.7.2. Then image build successfully and we get status healthy. Then after we hit this command "python image_to_animation.py drawings/garlic.png garlic_out" then we get error.
Traceback (most recent call last):
  File "image_to_animation.py", line 41, in <module>
    image_to_animation(img_fn, char_anno_dir, motion_cfg_fn, retarget_cfg_fn)
  File "image_to_animation.py", line 19, in image_to_animation
    image_to_annotations(img_fn, char_anno_dir)
  File "C:\Users\DELL4\AnimatedDrawings\examples\image_to_annotations.py", line 53, in image_to_annotations
    raise Exception(f"Failed to get bounding box, please check if the 'docker_torchserve' is running and healthy, resp: {resp}")
Exception: Failed to get bounding box, please check if the 'docker_torchserve' is running and healthy, resp: <Response [500]>
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/6b1048f2-e4eb-4c16-94e0-8d08768a1174)
![Screenshot 2024-01-09 204931](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/4d627cc5-98ee-4b37-a143-bd357935dcec)

**Comment by lbj96347** [comment]
I guess Torchserve is failing because it doesn't have enough RAM. You may also try to increase RAM for docker. 

How about checking your RAM after u enter `python image_to_animation.py drawings/garlic.png garlic_out` ?

**Comment by gaurish1212** [comment]
Hy
How can i increase ram for docker. In my system have 32GB ram

**Comment by corporateGhost** [comment]
Same Question

**Comment by lbj96347** [comment]
@gaurish1212 in default, docker can use unlimited RAM in your system. 

After running `docker run -d --name docker_torchserve -p 8080:8080 -p 8081:8081 docker_torchserve`  

Try to get more detail from container : `docker exec -it docker_torchserve bash`

All logs while running docker_torchserve `cat /home/torchserve/logs/ts_log.log` 

Then we may figure out which part goes wrong. Or post it here. 

Also I found a simular issue: https://github.com/facebookresearch/AnimatedDrawings/issues/136

**Comment by lbj96347** [comment]
@gaurish1212 try it: https://github.com/facebookresearch/AnimatedDrawings/issues/240#issuecomment-1784019869

**Comment by corporateGhost** [comment]
> @gaurish1212 try it: [#240 (comment)](https://github.com/facebookresearch/AnimatedDrawings/issues/240#issuecomment-1784019869)

I tried this. I changed it from RUN pip install torch to RUN pip install torch==2.0.0
but still it gives me the same error

**Comment by corporateGhost** [comment]
> @gaurish1212 by default, docker can use unlimited RAM in your system.
> 
> After running `docker run -d --name docker_torchserve -p 8080:8080 -p 8081:8081 docker_torchserve`
> 
> Try to get more detail from container : `docker exec -it docker_torchserve bash`
> 
> All logs while running docker_torchserve `cat /home/torchserve/logs/ts_log.log`
> 
> Then we may figure out which part goes wrong. Or post it here.
> 
> Also I found a simular issue: #136


I tried this and I am getting this 
(base) H:\AnimatedDrawings\torchserve>docker exec -it docker_torchserve bash
(base) root@6eab2021b0eb:/# cat /home/torchserve/logs/ts_log.log
cat: /home/torchserve/logs/ts_log.log: No such file or directory

**Comment by lbj96347** [comment]
@corporateGhost if u can't see `ts_log.log` , u can try to run bash inside docker container. 

step 1: 

> docker exec -it docker_torchserve bash

step 2:

> torchserve --stop 

step3: 

> /opt/conda/bin/torchserve --start --ts-config /home/torchserve/config.properties

Now you can see logs popping up.

**Comment by gaurish1212** [comment]
We didn't get any output
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/4dad36c5-3f26-4d72-83a4-6fa9e4177a6f)
This is my docker image
![image](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/fe4520a4-b61c-4949-9dc5-62dbab571a6e)

**Comment by gaurish1212** [comment]
> @corporateGhost if u can't see `ts_log.log` , u can try to run bash inside docker container.
> 
> step 1:
> 
> > docker exec -it docker_torchserve bash
> 
> step 2:
> 
> > torchserve --stop
> 
> step3:
> 
> > /opt/conda/bin/torchserve --start --ts-config /home/torchserve/config.properties
> 
> Now you can see logs popping up.

Plaese Reply

**Comment by gaurish1212** [comment]
![Screenshot 2024-03-27 195402](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/dbe5aa3f-4ee9-4fa4-9c5e-cada15a73970)
![Screenshot 2024-03-27 195344](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/f8d3c254-d6b4-42f5-8f66-ef096386c397)
![Screenshot 2024-03-27 195335](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/c87f58ce-4bb2-4a90-ba0c-bed61dc7e874)
![Screenshot 2024-03-27 195320](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/4d3528f2-5b6f-4443-ac6f-ffe3cd1f28db)
![Screenshot 2024-03-27 195252](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/2e3afe88-fb9b-4466-b658-9c8550db15af)
![Screenshot 2024-03-27 195227](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/d82d800d-d77b-4c34-b7f6-84153221f62a)
![Screenshot 2024-03-27 195213](https://github.com/facebookresearch/AnimatedDrawings/assets/137153727/a61986d0-d695-494f-b211-c58a992496b8)
This is my docker logs image what's wrong and how can i fix ?

**Comment by hjessmith** [comment]
I just merged a PR that deals with the Docker not correctly building. Please try pulling the latest version of the Animated Drawings code and following the installation steps again. Changing mmcv-full version as you did is triggering an assertion error in the torchserve handler code which is causing it to fail.

**Comment by gaurish1212** [comment]
solved thanks
