### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'decode'

### ISSUE THREAD

**Issue by hetianlong88** [facebookresearch/AnimatedDrawings#263]
After starting up a Python interpreter.
(animated_drawings) root@container:~/AnimatedDrawings# python
Python 3.8.13 (default, Oct 21 2022, 23:50:54) 
[GCC 11.2.0] :: Anaconda, Inc. on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from animated_drawings import render
>>> render.start('./examples/config/mvc/export_mp4_example.yaml')
/root/miniconda3/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65544) b'X11: The DISPLAY environment variable is missing'
  warnings.warn(message, GLFWError)
/root/miniconda3/envs/animated_drawings/lib/python3.8/site-packages/glfw/__init__.py:912: GLFWError: (65537) b'The GLFW library is not initialized'
  warnings.warn(message, GLFWError)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/root/AnimatedDrawings/animated_drawings/render.py", line 17, in start
    view = View.create_view(cfg.view)
  File "/root/AnimatedDrawings/animated_drawings/view/view.py", line 47, in create_view
    return WindowView(view_cfg)
  File "/root/AnimatedDrawings/animated_drawings/view/window_view.py", line 34, in __init__
    self._create_window(*cfg.window_dimensions)  # pyright: ignore[reportGeneralTypeIssues]
  File "/root/AnimatedDrawings/animated_drawings/view/window_view.py", line 126, in _create_window
    logging.info(f'OpenGL Version: {GL.glGetString(GL.GL_VERSION).decode()}')  # pyright: ignore[reportGeneralTypeIssues]
AttributeError: 'NoneType' object has no attribute 'decode'

What's going to happen to this problem?
Installing Ubuntu 18.04 operating system,GPU TITAN Xp(12GB).

**Comment by hetianlong88** [comment]
Installing Ubuntu 18.04 operating system.

**Comment by lbj96347** [comment]
If `echo $DISPLAY` returns nothing, then try `export DISPLAY=:0.0` before running all sample.

**Comment by hetianlong88** [comment]
thanks，It's been resolved.

**Comment by tianruci** [comment]
> export DISPLAY=:0.0

hey but how ..
