### ISSUE TITLE
docker start fail

### ISSUE THREAD

**Issue by adrianhsm** [facebookresearch/AnimatedDrawings#265]
1. docker start should also specify the volumn binding of directory, that is add "-v torchserve:/home", or start in readme will fail as no config file is found
2. the mar file should also copy to torchserve/torchserve/model-store

**Comment by SinianLiu** [comment]
hi, I changed the torch to torch==2.0.0, and also tried torch==2.0.1, it still didn't work.
Before that I also changed <RUN mim install mmcv-full==1.7.0> to <RUN mim install mmcv-full>.

Did you find a way to work it out?

**Comment by adrianhsm** [comment]
could you show the failure log?

**Comment by SinianLiu** [comment]
[torchserve_logs.txt](https://github.com/facebookresearch/AnimatedDrawings/files/14187265/torchserve_logs.txt)
Sure, I attached the docker logs for the touchserver, but it's very long..
Thank you so much!

**Comment by adrianhsm** [comment]
I see this error before, I guess you should not change the mmcv version

**Comment by adrianhsm** [comment]
as I post in another issue:
Change mmcv to 1.7.2 may lead the success of the building, but fail during runnig

**Comment by adrianhsm** [comment]
need to bind any directory actually
