### ISSUE TITLE
torchserve docker build fail

### ISSUE THREAD

**Issue by adrianhsm** [facebookresearch/AnimatedDrawings#266]
1. not torch version is specified, in my case, it is download pytorch 2.1.0, which seems not compatible with mmcv 1.7.0
2. Change mmcv to 1.7.2 may lead the success of the building, but fail during runnig
3. Change torch to 1.13.1 may lead to the error of "distribution not found"
4. Set torch to 2.0.0 seems ok in building and "python image_to_animation.py drawings/garlic.png garlic_out" works fine

**Comment by javier-pkg-mda** [comment]
Had same error, fixed by pinning torchserve to this version:
torch==2.0.1

**Comment by hjessmith** [comment]
Merged PR #275, which addressed docker build fail
