### ISSUE TITLE
ModuleError: No module named "ts.torch_handler.mmdet_handler"

### ISSUE THREAD

**Issue by richmonde** [facebookresearch/AnimatedDrawings#269]
Tried installing on ubuntu 22.04 , 20.04 and 18.04 in vmware and WSL2 according to README
Just changed the torch line into torch==2.0.0
But they all raise the same error above so that backend workers died.

**Comment by hjessmith** [comment]
Hi @richmonde 

That's a new error to me. Sounds like not everything was properly installed. I just merged a PR that dealt with errors in Dockerfile build step. Try grabbing the more recent version of the code and see if you still run into this error. There's also a script for getting torchserve running locally on macos if that's useful for you,
