### ISSUE TITLE
KeyError: 'animated_drawings\\mvc_base_cfg.yaml'

### ISSUE THREAD

**Issue by lyyilin** [facebookresearch/AnimatedDrawings#279]
Microsoft Windows [版本 10.0.22631.3447]
(c) Microsoft Corporation。保留所有权利。
>> Successfully save config file for character in F:\\myitem2\\old world\\AnimatedDrawings-main\\drawings\wu\character_config.yaml !!
>> Successfully save cropped image file for character in F:\\myitem2\\old world\\AnimatedDrawings-main\\drawings\wu\cropped_image.png !!
>> Successfully save segmented image file for character in F:\\myitem2\\old world\\AnimatedDrawings-main\\drawings\wu\mask_image.png !!
>>> Motion information acquire
>>> Acquire Motion from video
D:\Anconda\envs\animated_drawings\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py:69: UserWarning: Specified provider 'CUDAExecutionProvider' is not in available provider names.Available providers: 'AzureExecutionProvider, CPUExecutionProvider'
  warnings.warn(
>>> Pose Model loaded: F:\myitem2\old world\AnimatedDrawings-add-monocular-video-input\examples\offline_lib\pose3d\vitpose/checkpoints/vitpose-b-coco.onnx
>>> Running inference on F:\\myitem2\\old world\\AnimatedDrawings-add-monocular-video-input\\examples\\drawings\\dance.mp4
  0%|                                                                                                                                                     | 0/189 [00:00<?, ?it/s]Loading F:\myitem2\old world\AnimatedDrawings-add-monocular-video-input\examples\offline_lib\pose3d\vitpose\checkpoints\yolov8\yolov8l.onnx for ONNX Runtime inference...
'Requirement' object has no attribute 'name'
 99%|██████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████▎| 188/189 [00:25<00:00,  7.30it/s]
>>> Mean inference FPS: 7.33
>>> Total poses predicted: 85 mean per frame: 0.45
>>> Mean FPS per pose: 3.31
>>> Keypoint2d and keypoint_2d npz save in  output_2dhpe_npz\dance_2dhpe.npz
>> Successfully predicted 2D keypoints!!
>>> Supported onnxruntime version:  1.17.3
>>> Supported Opset versions:  ['AzureExecutionProvider', 'CPUExecutionProvider']
100%|███████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 1/1 [00:04<00:00,  4.43s/it]
>> Successfully predicted 3D keypoints!!
>> Generating bvh file...
>>> Sucessfully save *.bvh file in output_3dhpe_bvh\dance_smartbody.bvh
>>> Sucessfully saved *.bvh file
>>> Bind bvh successfully!!
>>> Regenerate config files successfully, the main config file stored in F:\myitem2\old world\AnimatedDrawings-add-monocular-video-input\examples\tmp\main_cfg.yaml
Traceback (most recent call last):
  File "offline_demo.py", line 184, in <module>
    render.start(main_cfg_path)
  File "D:\Anconda\envs\animated_drawings\lib\site-packages\animated_drawings-0.0.0-py3.8.egg\animated_drawings\render.py", line 13, in start
  File "D:\Anconda\envs\animated_drawings\lib\site-packages\animated_drawings-0.0.0-py3.8.egg\animated_drawings\config.py", line 19, in __init__
  File "D:\Anconda\envs\animated_drawings\lib\site-packages\pkg_resources\__init__.py", line 1160, in resource_filename
    return get_provider(package_or_requirement).get_resource_filename(
  File "D:\Anconda\envs\animated_drawings\lib\site-packages\pkg_resources\__init__.py", line 1862, in get_resource_filename
    return self._extract_resource(manager, zip_path)
  File "D:\Anconda\envs\animated_drawings\lib\site-packages\pkg_resources\__init__.py", line 1883, in _extract_resource
    timestamp, size = self._get_date_and_size(self.zipinfo[zip_path])
KeyError: 'animated_drawings\\mvc_base_cfg.yaml'

**Comment by hjessmith** [comment]
@Brian417-cup have you encountered this before?

**Comment by Brian417-cup** [comment]
@lyyilin  can you offer the detailed input command? Judging from the current situation, the configuration files related to the monocular video here have been successfully generated, but there is a problem in the animation process in Animated Drawings. Are the paths you provided earlier all absolute?
