### ISSUE TITLE
How can we add new motion?

### ISSUE THREAD

**Issue by gaurish1212** [facebookresearch/AnimatedDrawings#280]
Please help me.
How can we add new motion ?

**Comment by hjessmith** [comment]
Instructions on how to do this are [here](https://github.com/facebookresearch/AnimatedDrawings?tab=readme-ov-file#using-bvh-files-with-different-skeletons)

**Comment by gaurish1212** [comment]
How can we create motion and retarget file?

**Comment by hjessmith** [comment]
Have you tried searching the closed issues for a solution? In particular, #152 might be useful
