### ISSUE TITLE
Is there the code for training the  figure detection and pose estimation model

### ISSUE THREAD

**Issue by manjaro1124** [facebookresearch/AnimatedDrawings#287]

**Comment by manjaro1124** [comment]
I want to finetune  the figure detection and pose estimation model with the dataset, but it don't have the dataset _load function

**Comment by Brian417-cup** [comment]
@manjaro1124, author has said in the thesis their train and test stages are implemented by [MMPose](https://github.com/open-mmlab/mmpose)  and [MMDet](https://github.com/open-mmlab/mmdetection) framework, so you should combine corresponding config files and then train or finetune,
