### ISSUE TITLE
Its this normal? glitch in the bottom

### ISSUE THREAD

**Issue by MrPepsiman01** [facebookresearch/AnimatedDrawings#289]
![video](https://github.com/facebookresearch/AnimatedDrawings/assets/157427946/d9993131-5eda-48f8-b69a-5ab2cd160e4a)

Have this glitch in all of my draws and the default draws

**Comment by hjessmith** [comment]
This is not normal, I've never seen it. Can you provide some information about your development environment?

**Comment by MrPepsiman01** [comment]
Sure, what would be the command to view the logs? (I'm still learning, this is for a kindergarten)

**Comment by hjessmith** [comment]
I mean like what operating system and type of computer (chromebook, PC, mac, cloud instance, etc.) are you running into this issue on? There also should be a log.txt file that gets created when you run the code. Sharing that would be useful.
