### ISSUE TITLE
InvalidKeyException

### ISSUE THREAD

**Issue by cosmos223** [facebookresearch/AnimatedDrawings#295]
I have started TorchServe on macOS using docker according to the Installation, but the response to http://localhost:8080/ping is as follows and does not work.

Dockerfile is not changed, and the specified version of anaconda python is used.

```
{
  "code": 400,
  "type": "InvalidKeyException",
  "message": "Token Authorization failed. Token either incorrect, expired, or not provided correctly"
}
```

What should I do?

**Comment by z1ouhan** [comment]
Use  ` torchserve --start --disable-token-auth`  to start the service.
reference: https://github.com/pytorch/serve/blob/master/docs/token_authorization_api.md

**Comment by frnzee** [comment]
> Use ` torchserve --start --disable-token-auth` to start the service. reference: https://github.com/pytorch/serve/blob/master/docs/token_authorization_api.md

Can confirm it's working. Thank you!

**Comment by cosmos223** [comment]
It works perfectly! Thank you!

**Comment by hjessmith** [comment]
@cosmos223, @z1ouhan, @frnzee 

If any of you would like to submit a PR with the change that worked for you, I'd be happy to merge it.

**Comment by nikste** [comment]
this should also be updated in the getting started guide:
https://github.com/pytorch/serve/blob/master/docs/getting_started.md
