### ISSUE TITLE
docker failed

### ISSUE THREAD

**Issue by Ellen-2018** [facebookresearch/AnimatedDrawings#298]
(animated_drawings) root@iZmj7apgrkrc74erbt5rt4Z:~/mywork/AnimatedDrawings/torchserve# docker run -d --name docker_torchserve -p 8080:8080 -p 8081:8081 docker_torchserve
a49cdc409dccf777dda22ef4d316fadf35dba2c49f70643d8be2c166451e0346

after Waiting ~10 seconds,
(animated_drawings) root@iZmj7apgrkrc74erbt5rt4Z:~/mywork/AnimatedDrawings/torchserve# curl http://localhost:8080/ping
{
"code": 400,
"type": "InvalidKeyException",
"message": "Token Authorization failed. Token either incorrect, expired, or not provided correctly"
}

**Following the steps in the documentation, if it reports an error as above, what are the requirements for the cuda environment to build the docker image? For example, the version of cuda and GPU driver.**

**Comment by hjessmith** [comment]
I've just merged a PR addressing this issue. Please pull latest version of main branch and let me know if the issue persists.

**Comment by ggxxii** [comment]
I've met the same issue, but in my case I' running torchserve on a remote Linux. I've tried address http://0.0.0.0:8080; https://127.0.0.1:8443 for inference, both give the same error when test curl with ping. What went wrong??? Plz help!

**Comment by ggxxii** [comment]
> I've just merged a PR addressing this issue. Please pull latest version of main branch and let me know if the issue persists.

Adding "--disable-token-auth" indeed worked! Thanks!
