### ISSUE TITLE
Upload custom BVH to web version

### ISSUE THREAD

**Issue by jumpjack** [facebookresearch/AnimatedDrawings#300]
Can you please add the ability to upload custom BVH files?
There are some hundreds of BVH files available here: https://sites.google.com/a/cgspeed.com/cgspeed/motion-capture?authuser=0

**Comment by hjessmith** [comment]
This functionality already exists. See the instructions in this section of the ReadMe:
https://github.com/facebookresearch/AnimatedDrawings?tab=readme-ov-file#creating-your-own-bvh-files

**Comment by jumpjack** [comment]
I was talking about web version.
