### ISSUE TITLE
how to set Motion and Retarget file when Creating Your Own BVH Files

### ISSUE THREAD

**Issue by xiaomomo** [facebookresearch/AnimatedDrawings#85]
the project is excellent， but when i try "Creating Your Own BVH Files" ，i don't know how to set Motion and Retarget file , does it has some document? thank you!

**Comment by hjessmith** [comment]
Hello @xiaomomo. I appreciate the positive sentiment about the project. 

Regarding the motion and retarget configuration files, there is information about how to create them in the [config file README](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md). Once you've created them, specify the file paths within the top-level/mvc config file. See this [top-level config](https://github.com/evdcush/AnimatedDrawings/blob/main/examples/config/mvc/interactive_window_example.yaml) file as an example.

Let me know if you need more guidance, and thanks for engaging with the project!

**Comment by xiaomomo** [comment]
> Hello @xiaomomo. I appreciate the positive sentiment about the project.
> 
> Regarding the motion and retarget configuration files, there is information about how to create them in the [config file README](https://github.com/facebookresearch/AnimatedDrawings/blob/main/examples/config/README.md). Once you've created them, specify the file paths within the top-level/mvc config file. See this [top-level config](https://github.com/evdcush/AnimatedDrawings/blob/main/examples/config/mvc/interactive_window_example.yaml) file as an example.
> 
> Let me know if you need more guidance, and thanks for engaging with the project!

OK, i change the "up" parameter in  motion file, it worked, thanks a lot!
