### ISSUE TITLE
Transparent mp4

### ISSUE THREAD

**Issue by Joshalphonse** [facebookresearch/AnimatedDrawings#94]
Can I make a transparent mp4 too?

**Comment by hjessmith** [comment]
Is transparency even supported with .mp4? Unless it's a matter of specifying a particular codec for [OpenCV's VideoWriter](https://docs.opencv.org/3.4/dd/d9e/classcv_1_1VideoWriter.html) to use, it isn't currently allowed. 

If you want to specify a particular codec, you can do so within the top-level (mvc) config, as exampled here:
https://github.com/facebookresearch/AnimatedDrawings/blob/827b2f65549f906e5a8ed8aa7cbcfc2150d47d36/animated_drawings/mvc_base_cfg.yaml#L19
