### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'eglGetCurrentContext'

### ISSUE THREAD

**Issue by justinduynguyen** [facebookresearch/AnimatedDrawings#96]
![image](https://user-images.githubusercontent.com/18099515/231950994-41fcddbd-b9e8-4960-ae38-5e8d01aeae8b.png)

I got this error when run the code:
```
from animated_drawings import render
render.start('./examples/config/mvc/interactive_window_example.yaml')
```
Ubuntu 18.04

**Comment by justinduynguyen** [comment]
I fixed this issue by run:
`sudo apt-get install libosmesa6-dev freeglut3-dev`
But now i got another error:
`OpenGL.error.Error: Attempt to retrieve context when no valid context` and this window
![image](https://user-images.githubusercontent.com/18099515/232028943-c5fddae6-e5bb-4908-9084-c20ba8844d61.png)

**Comment by odalton** [comment]
@justinduynguyen I got the exact same issue running this in Ubuntu on WSL windows 11.
- Resolved this by first getting the OpenGL running locally first.
  - see: https://stackabuse.com/brief-introduction-to-opengl-in-python-with-pyopengl/

`import OpenGL
import OpenGL.GL
import OpenGL.GLUT
import OpenGL.GLU
print("Imports successful!")
from animated_drawings import render
render.start('interactive_window_example.yaml')`

Followed your install + added some extras.
1. sudo apt-get install libosmesa6-dev freeglut3-dev
2. sudo apt-get install libglfw3-dev libgles2-mesa-dev
3. sudo apt-get install libosmesa6
4. **export PYOPENGL_PLATFORM=osmesa** - think this is what fixed the GLUT OpenGL issue

<img width="756" alt="image" src="https://user-images.githubusercontent.com/5709330/232058639-cea165ec-abdd-4a3c-8c67-b847351d38ab.png">

**Comment by hjessmith** [comment]
@justinduynguyen , @odalton thank you for sharing what you've found here, much appreciated.

@justinduynguyen, please close this issue if odalton's steps resolved things for you.

**Comment by liudan193** [comment]
> @justinduynguyen I got the exact same issue running this in Ubuntu on WSL windows 11. FYI i downgraded the python version also to 3.8.10
> 
> * Resolved this by first getting the OpenGL running locally first.
>   
>   * see: https://stackabuse.com/brief-introduction-to-opengl-in-python-with-pyopengl/
> 
> ```
> import OpenGL
> import OpenGL.GL
> import OpenGL.GLUT
> import OpenGL.GLU
> print("Imports successful!")
> from animated_drawings import render
> render.start('interactive_window_example.yaml')
> ```
> 
> Followed your install + added some extras.
> 
> 1. sudo apt-get install libosmesa6-dev freeglut3-dev
> 2. sudo apt-get install libglfw3-dev libgles2-mesa-dev
> 3. sudo apt-get install libosmesa6
> 4. **export PYOPENGL_PLATFORM=osmesa** - think this is what fixed the GLUT OpenGL issue
>    4.1.  see: https://pyrender.readthedocs.io/en/latest/examples/offscreen.html
> 
> <img alt="image" width="756" src="https://user-images.githubusercontent.com/5709330/232058639-cea165ec-abdd-4a3c-8c67-b847351d38ab.png">
> 
> ```
> from setuptools import find_packages, setup
> 
> setup(
>     name='animated_drawings',
>     description="Companion code for `A Method For Automatically Animating Children's Drawings of the Human Form.`",
>     author='FAIR',
>     author_email='jesse.smith@meta.com',
>     python_requires='>=3.8.10',
>     install_requires=[
>         'numpy== 1.23.3',
>         'scipy==1.9.3',
>         'scikit-image==0.19.3',
>         'scikit-learn==1.1.2',
>         'shapely==1.8.5.post1',
>         'opencv-python==4.6.0.66',
>         'Pillow==9.3.0',
>         'glfw==2.5.5',
>         'PyOpenGL==3.1.6',
>         'PyYAML==6.0',
>         'requests==2.28.1',
>         'torchserve==0.7.0',
>         'tqdm==4.64.1',
>         'Flask==2.2.3'
>     ],
>     packages=find_packages(),
> )
> ```

Thanks for your solution.
