### ISSUE TITLE
Application for overlays?

### ISSUE THREAD

**Issue by saifrahmed** [facebookresearch/AnimatedDrawings#97]
Firstly, this is supreme! Both kids have been glued to it since getting out of school today!

This is unrelated to the codebase and specific to the header image/video you have - you have the animations overlayed on another video, which application did you use to achieve this?

**Comment by hjessmith** [comment]
Hey thanks! I did the animation overlay with Adobe Premiere. 

If you're short and cash and (very) long on time, however, you could achieve this effect by doing a frame-by-frame overlay with a photo-compositing library ( Python Imaging Library, OpenCV, etc.), then creating an animation from the frames with FFMPEG.
